### ISSUE TITLE
Foliage grows far too quickly.

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#2045] opened 2015-05-17 13:07 UTC
Title says it all.

**Comment by bearbin** [comment] 2015-05-17 13:30
Trees and wheat also grow at night. They should only grow during the day or if illuminated by a torch.

**Comment by NiLSPACE** [comment] 2015-05-17 13:57
I changed the name, because every type of plant grows too fast.

**Comment by s32ialx** [comment] 2015-05-17 17:16
except grass grows to slow 1 hour and not even half of my patch of maybe 40x20 grew

**Comment by mathiascode** [comment] 2020-03-19 12:06
Duplicate of #1667

**Closed** 2020-03-19 12:06 UTC
