### ISSUE TITLE
Mobs ignore the sunlight when standing on flowers/grass/mushrooms 

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#3101] opened 2016-03-28 21:28 UTC
I get attacked a lot during the day, by skeletons standing in the open when the sun is shining.

**Comment by NiLSPACE** [comment] 2016-03-28 21:38
Are they in long grass by any chance?

**Comment by jammet** [comment] 2016-03-28 23:05
It happens on flat terrain without grass.

**Comment by 109C** [comment] 2016-03-29 01:06
@jammet Did you try pushing them out of the flowers? They might think the flower blocks sunlight.

**Comment by jammet** [comment] 2016-03-29 01:07
I've been attacked by them when they weren't standing on flowers, or
anything but plain grass blocks. In the screenshot you can't see that, but
it happens. Will double check tomorrow.

**Comment by NiLSPACE** [comment] 2016-03-29 06:56
Yes, of course, but it brings us close to the problem ^ ^

**Comment by LogicParrot** [comment] 2016-03-29 12:00
This is a dupe of #1926:
>Happens with all little objects like flowers, bushes, etc.

I added flowers to the title, just in case.

I'll keep this open for now,to keep it on top and avoid further dupes. This is probably the survival issue that got the most dupes, this indicates we should fix it fast. I'll work on it next.

**Comment by jammet** [comment] 2016-03-29 12:13
Before I possibly make another dupe XD, I hope something can be done about
the spawning behaviour of all aggressive mobs. They seem to spawn in areas
that are well lit, too.

Quite a few more than I seem to remember from Vanilla. I mean ... one
minute there's nothing there, one minute later, there is a full scale war
by my front door...

**Comment by LogicParrot** [comment] 2016-03-29 12:27
@jammet That would be #2159. I will be removing both your and my comments after a while to keep things tidy :)

**Closed** 2016-04-06 06:33 UTC
Labels: lighting
