### ISSUE TITLE
raspberry pi zero Support issues

### ISSUE THREAD

**Issue by MoYuHengFei** [cuberite/cuberite#5280] opened 2021-08-15 04:28 UTC
Client version: x.x.x
Server OS: Raspbian buster
Cuberite Commit id: 
Can't run on raspberry pi zero

**Comment by bearbin** [comment] 2021-08-15 12:50
This is a known tradeoff of the pre-compiled builds configuration. The raspi builds will not run on the Zero but will run with greater performance on other models. If you want to use the Zero, you need to compile yourself, the recommended technique is the `compile.sh` script:

```sh -c "$(wget -O - https://compile.cuberite.org)"```

Closing as dupe of #4774

**Closed by bearbin** 2021-08-15 12:50 UTC
