### ISSUE TITLE
Invisible Mobs attacking

### ISSUE THREAD

**Issue by xylence** [cuberite/cuberite#4016] opened 2017-09-10 12:50 UTC
Client version:   1.8.9 / 1.12.1
Server OS:        Linux (Debian 8 minimal)
Commit id:        c334824199fcddde9f5a712a08a54db798965890

### Expected behavior
Seeing the mobs so you can 'do something against them' ?

### Actual behavior
Mobs are invisible and attack you

### Steps to reproduce the behavior
Play in survival mode..

**Comment by Bond-009** [comment] 2017-09-10 12:54
Duplicate of #3696

**Closed** 2017-09-10 13:08 UTC
