### ISSUE TITLE
1.11 - invisible skeletons and dark arrows

### ISSUE THREAD

**Issue by PolishPROGamer** [cuberite/cuberite#3597] opened 2017-02-27 20:00 UTC
Client version:   1.11 and above, Vanilla, OS - Windows
Server OS:        Linux
Only shadows are visible
P.S.
Oh, sorry - I've just read "Add 1.11.1/1.11.2 protocol" you already know this xD
![2017-02-27_20 16 30](https://cloud.githubusercontent.com/assets/26070866/23377283/b9cdad24-fd2f-11e6-82b8-698917729114.png)
![2017-02-27_20 18 24](https://cloud.githubusercontent.com/assets/26070866/23377285/bcab81e2-fd2f-11e6-89cd-fc3522f4fe7e.png)
![2017-02-27_20 22 27](https://cloud.githubusercontent.com/assets/26070866/23377287/be435926-fd2f-11e6-8122-98e59d8baccd.png)

**Comment by Pokechu22** [comment] 2017-02-27 23:21
Skeletons are known to be broken, but the fact that they have shadows implies the entity does exist.  Interesting.  Does punching the place where the skeleton should be cause the game to go all black / "creepypasta mode" when taking screenshots?  If so, this sounds a lot like what I found on #3135 in [this comment](https://github.com/cuberite/cuberite/pull/3135#issuecomment-211606976); probably, it's a malformed bit of entity metadata that causes rendering to stop partway though.  (Even if creepypasta mode isn't a thing, the invisibility is still probably caused by something like this)

**Comment by PolishPROGamer** [comment] 2017-02-28 17:29
English isn't my native language, I don't fully understand you, but I can't do something strange like black screen or skeletons visible on screenshots...
Skeletons can be set on fire!
![2017-02-28_18 02 27](https://cloud.githubusercontent.com/assets/26070866/23416244/605cf124-fde2-11e6-93ef-5d3ead915ff9.png)
Generally at night:
[log.zip](https://github.com/cuberite/cuberite/files/807599/log.zip)
Logs spammed by:
`java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at zm.di(SourceFile:266) ~[1.11.2.jar:?]
	at bml.a(SourceFile:48) ~[1.11.2.jar:?]
	at bvl.a(SourceFile:141) [1.11.2.jar:?]
	at bvq.a(SourceFile:41) [1.11.2.jar:?]
	at bvq.a(SourceFile:16) [1.11.2.jar:?]
	at bur.a(SourceFile:359) [1.11.2.jar:?]
	at bur.a(SourceFile:346) [1.11.2.jar:?]
	at bqm.a(SourceFile:604) [1.11.2.jar:?]
	at bqe.a(SourceFile:1282) [1.11.2.jar:?]
	at bqe.b(SourceFile:1187) [1.11.2.jar:?]
	at bqe.a(SourceFile:1032) [1.11.2.jar:?]
	at bes.av(SourceFile:993) [1.11.2.jar:?]
	at bes.a(SourceFile:398) [1.11.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [1.11.2.jar:?]
[18:15:43] [Client thread/ERROR]: Couldn't render entity`

**Comment by Pokechu22** [comment] 2017-02-28 18:52
Sorry, I'll try to use simpler English:

That information shows what I expected; the problem is caused by broken [entity metadata](http://wiki.vg/Entities).  The log you posted shows that.

Reading that log shows that the problem happens when the game tries to draw the skeleton - it needs to know if the skeleton is moving its arms (metadata field 12), but Cuberite incorrectly sends the information that says whether it is or not.  Instead of getting a yes/no value (a Boolean), the game receives a number (an Integer), and doesn't know what to do with that and thus doesn't draw the skeleton.

It will take some work to fix this problem, because 1.11 changed a lot about skeletons, but it should be possible to fix.

What I said about the screen going black was what happened with wolves in the past, but it's not unusual that the game works differently in this case.

**Closed** 2017-03-03 09:59 UTC
