### ISSUE TITLE
restart command doesn't bring the server up again

### ISSUE THREAD

**Issue by GTP95** [cuberite/cuberite#4014] opened 2017-09-10 08:05 UTC
Client version:   x.x.x
Server OS:        Android
Commit id:        approx: c334824199fcddde9f5a712a08a54db798965890

### Expected behavior
restart command stops the server and then starts it again

### Actual behavior
The restart command, either issued via console or via Cuberite WebAdmin, stops the server but doesn't start it again

### Steps to reproduce the behavior

Send the restart command then wait. The server will stop but never come up again.

**Comment by Bond-009** [comment] 2017-09-10 09:11
Duplicate of #3177

**Comment by bearbin** [comment] 2017-09-10 09:15
Closing as duplicate.

**Closed by bearbin** 2017-09-10 09:15 UTC
Labels: ingame/commands & ranks & chat
