### ISSUE TITLE
Can't open commandblock

### ISSUE THREAD

**Issue by Sjoerrdd** [cuberite/cuberite#3946] opened 2017-08-22 10:55 UTC
Client version:  1.12
Server OS:        Linux (RPI)
Commit id:       e44a0adfcf623b37ee26f79e607f81dc16fac75e

### Expected behavior
Use a commandblock (enter command)

### Actual behavior
Nothing, GUI doesn't open

### Steps to reproduce the behavior
Place a commandblock, rightclick on it

**Comment by Bond-009** [comment] 2017-08-22 11:26
Duplicate of #3223

**Closed** 2017-08-22 11:29 UTC
