### ISSUE TITLE
Late gamemode change

### ISSUE THREAD

**Issue by coolcats2000** [cuberite/cuberite#4207] opened 2018-04-04 14:15 UTC
Client version:   1.12.2
Server OS:        Linux(Raspbian)
Commit id:        1991a5b0e6a220a37e42c91e8448f4e7a786b767

### Expected behavior
Gamemode changes as soon as you warp into the world using signs

### Actual behavior
Gamemode changes only when you warp out of the world using signs

### Steps to reproduce the behavior
1.Create 2 worlds
2.Set one world to gamemode 0 and second world to gamemode 1
3.Warp between the worlds using signs

**Comment by changyongGuo** [comment] 2018-07-01 14:12
Hi,

This issue is caused by lack of game mode set in method cPlayer::DoMoveToWorld.
I will submit a fix for this.

Best regards
Changyong

**Closed** 2018-07-22 23:35 UTC
