### ISSUE TITLE
Forgetful schema still overwriting world

### ISSUE THREAD

**Issue by r-tanner-f** [cuberite/cuberite#3387] opened 2016-10-02 01:52 UTC
Seems `Schema=Forgetful` is being ignored. The world is being saved anyway.

Client version:   1.10.2
Server OS:        Windows/Linux/macOS/BSD/...
Commit id:        c83b051c1a3e68fc9315ffffb277dc3da86cf02a
### Expected behavior

After setting storage schema to forgetful, Cuberite should not save the world on exit.
### Actual behavior

Cuberite saves the world on exist. It is very much not forgetful, and more like an elephant. :)
### Steps to reproduce the behavior

Add the following to `settings.ini`:

```
[Storage]
Schema=Forgetful
```

Spin up Cuberite. Make changes to the world. Exit Cuberite. Start Cuberite again. Observe that changes are not forgotten.

**Comment by madmaxoft** [comment] 2016-10-02 08:23
The `Schema=Forgetful` setting needs to be in the `world.ini` for the world which is to use the forgetful schema, not in settings.ini.

**Comment by madmaxoft** [comment] 2016-11-20 19:09
Did you get your intended behavior after moving the configuration to the world.ini file? Can we close this issue report?

**Comment by mathiascode** [comment] 2017-08-11 00:30
Forgetful works as intended. This issue can be closed.

**Closed** 2017-08-11 17:48 UTC
Labels: status/needs confirmation
