### ISSUE TITLE
Walls of random blocks in loading chunks

### ISSUE THREAD

**Issue by bramvdbogaerde** [cuberite/cuberite#2405] opened 2015-07-28 19:30 UTC
When chuncks are loading it displays walls of leaves. Is the normal behaviour? 

This is how it looks like:
![2015-07-28_21 26 03](https://cloud.githubusercontent.com/assets/2016763/8941420/b17ff53e-356f-11e5-974e-c9ff1dbce0dc.png)

Could this be caused by a high load on the server CPU?

**Comment by LO1ZB** [comment] 2015-07-28 19:48
Yes, it could be, I got that error with some crazy debug configuration too a few weeks ago.

**Comment by worktycho** [comment] 2015-07-28 20:07
That is a bug if high cpu can cause that.

**Comment by madmaxoft** [comment] 2015-07-28 21:23
That's weird, we already had this once and it had been fixed. It had been caused by sending SetBlock / SetBlocks packets for chunks that haven't been sent to the client yet.

**Comment by bramvdbogaerde** [comment] 2015-07-28 21:26
What commit was that? I could be possible that i'm running a slightly older version.

**Comment by NiLSPACE** [comment] 2015-07-28 21:36
It's been a while, maybe end of 2014, so that's probably not the issue,

**Comment by bramvdbogaerde** [comment] 2015-07-28 21:42
Yes indeed, my build was from a week ago.

**Comment by SphinxC0re** [comment] 2015-08-14 15:37
Can we close this. The issue seems to be solved

**Comment by NiLSPACE** [comment] 2015-08-14 15:47
Are you sure? For me it usually happens when I just transported to a different world (and back).

**Comment by SphinxC0re** [comment] 2015-08-14 16:07
Do we know where this comes from?

**Comment by madmaxoft** [comment] 2015-08-16 10:24
It might be caused by teleporting to another world of the same dimension.

The previous cause of the leaves walls was that blockchange packets were sent to a client even when they didn't have the respective chunk loaded. We added a check that only sends those packets for chunks already sent to the client; perhaps this check doesn't get reset when teleporting to another world?

**Comment by LO1ZB** [comment] 2015-08-16 11:02
I had this after I rejoint after I timed out due to a exreamly overloaded world-thread.

**Comment by jammet** [comment] 2015-09-03 12:32
I've had this several times, too. Usually when using nethergates to travel back and forth. That is still a sluggish process (which reported about sometime before). NilSPACE might have seen it, too, when he was on my server to test it.

![2015-07-06_13 39 30](https://cloud.githubusercontent.com/assets/11940735/9658231/33e0e1c4-5248-11e5-97b7-e9b6617f6074.png)
![2015-07-05_10 26 57](https://cloud.githubusercontent.com/assets/11940735/9658232/370ece92-5248-11e5-9810-d93d7bb4c8e1.png)
![2015-07-05_10 26 31](https://cloud.githubusercontent.com/assets/11940735/9658236/3b8052fc-5248-11e5-806e-c0df0f2eab9f.png)
![2015-07-05_10 26 57](https://cloud.githubusercontent.com/assets/11940735/9658242/4b40fe08-5248-11e5-84e7-c76d0f4ed5f4.png)

**Comment by LogicParrot** [comment] 2016-02-16 16:10
Related: #2315

**Comment by Schwertspize** [comment] 2016-02-16 17:43
We should keep that as a feature....

**Comment by LogicParrot** [comment] 2016-04-04 15:34
The walls in @bramvdbogaerde shot seem random. The walls in @jammet's shot seem to be a pattern repeating for each chunk.

**Comment by tigerw** [comment] 2016-04-04 18:52
Sortof fixed in #3115. Problem is/was that the block change packet is sent to unloaded chunks, or at least, can be caused by that.

**Comment by tigerw** [comment] 2016-04-04 18:52
Likely a client bug.

**Comment by LogicParrot** [comment] 2016-05-03 08:04
Might be somewhat related to #3182 , to `cChunkSender`, specifically.

**Comment by Pokechu22** [comment] 2016-06-06 19:21
I've been chasing down a similar bug recently.

First, a note on how Minecraft handles unloaded chunks.  From `ChunkProviderClient`:

```java
	@Override
	public Chunk provideChunk(int p_73154_1_, int p_73154_2_) {
		Chunk var3 = (Chunk) this.chunkMapping.getValueByKey(ChunkCoordIntPair
				.chunkXZ2Int(p_73154_1_, p_73154_2_));
		return var3 == null ? this.blankChunk : var3;
	}
```

`blankChunk` is an instance of `EmptyChunk`, which overrides a bunch of the get and set methods to do nothing or always return air.  But it doesn't override _all_ of the methods.  Importantly, `setBlockState` still sets the block in the (superclass') storage arrays.  And those storage arrays are used when rendering, not the `getBlock` method.  Worse, only one `getBlock` method is overridden to always return air, the one that takes a `BlockPos`.  The one that takes x, y, and z coordinates still works...  Also, both methods use `x & 15, y, z & 15` to get the block, so even if the coordinates would be in another chunk (the `EmptyChunk` is initialized with chunk coordinates at 0, 0) it'll still happily load the block.  It also doesn't override `getBlockState`, which is the most commonly used method for getting a block...

This is a client bug, no doubt about it.  It's a broken implementation.  But to work around it, cuberite needs to make sure that it doesn't send block update packets to chunks the client hasn't loaded yet, to keep this from happening.

The gist of the issue is that the client uses a single, shared `EmptyChunk` for all unloaded chunks, and while that chunk is supposed to always return air when getting blocks, it doesn't do that for all methods.  It also can be mutated in some cases, meaning that _all_ locations that use the shared empty chunk get the same changes.

**Comment by Pokechu22** [comment] 2016-06-07 00:01
Looking at the code, 1.9 made some internal changes so now there are only two methods, `getBlockState(BlockPos)` and `getBlockState(x, y, z)`.  `getBlockState(BlockPos)` is overridden to always return air, so this won't happen in 1.9.  `getBlockState(x, y, z)` is only used with maps (and internally to implement `getBlockState(BlockPos)`, so on the client there won't be any notable side-effects.  Even when rendering, `getBlockState` is used.  So, this won't appear as an issue in 1.9.  Nevertheless, the set block packets probably still shouldn't be sent in unloaded chunks.

**Comment by madmaxoft** [comment] 2016-06-07 07:36
@Pokechu22 please don't post Minecraft code. We're making a clean implementation of a server.

**Comment by tigerw** [comment] 2016-06-07 13:41
We can always benefit from some, ah, *guiding hints* though :P

I wonder how you know so much about the internals. MCP isn't out for 1.9 is it?

**Comment by Pokechu22** [comment] 2016-06-07 15:56
I feel like in this kind of case, _client_ code should be fine to post, since it's caused by an esoteric bug found in an old version that isn't documented anywhere else.  I do understand the issue with giving _server_ code, since server code would be a problem with implementation.  But we're not writing a client, so I feel like client code, particularly when discussing bugs caused by client issues, should be postable.

Worth noting - other client implementations that I've checked don't have this bug, since either they ignore block changes in unloaded chunks or create a _new_ empty chunk, rather than sharing the same empty chunk.  So it's really only an issue with the vanilla one (and only versions before 1.9 anyways).

[I've added a warning about this behavior to wiki.vg](http://wiki.vg/index.php?title=Protocol&diff=7959&oldid=7952).

---

There actually is a public 1.9 MCP beta build (searge posted it on his twitter a while ago).  I'm actually using a 1.9.4 build, though, which isn't public (it's the same one the optifine dev is using; it's based off of 1.9 with a 1.9.4 SRG file from forge, a script that removes annotations that were added and break a bunch of patches, and manual editing of other files that fail to compile; in general it's not completely stable but it _does_ work).  But 1.8.9 MCP was also used when investigating that bug.  (Also worth noting - I was looking at empty chunk bugs for reasons not directly related to cuberite; it just happened that he same issue applied here).

**Comment by Pokechu22** [comment] 2016-06-09 00:49
They actually just put the 1.9 and 1.9.4 builds of MCP on [the MCP website](http://www.modcoderpack.com/website/releases) if you're interested.

**Closed** 2016-08-29 11:32 UTC
Labels: worlds / chunks

**Comment by Pokechu22** [comment] 2016-11-05 22:28
Does someone have a copy of the large comment I posted here a while ago that explained why this happened (probably in email)?  I actually need it (I found a vanilla bug where the same analysis applies and would like to put a modified version of that same comment on the bug tracker), and it took a long time to write and I'd rather not rediscover what I already knew (and spent an hour _documenting_).

**Comment by LogicParrot** [comment] 2016-12-26 16:18
I think you might have explained portions of this in several related threads and PRS, that large comment could still be in Github somewhere.
