### ISSUE TITLE
raspi-armhf #1222 binary fails on armv6l RPi models

### ISSUE THREAD

**Issue by MichaIng** [cuberite/cuberite#4774] opened 2020-07-12 11:35 UTC
Board: RPi `armv6l`/`armhf`
Server OS: `Raspbian`
Cuberite Commit id: `1222`

### Expected behavior
Server binary executes

### Actual behavior
"Illegal instruction"

### Steps to reproduce the behavior
0. Boot an ARMv6 RPi model: RPi1, Zero or Zero W
1. Download the current raspi-armhf build: https://download.cuberite.org/linux-armhf-raspbian/Cuberite.tar.gz
2. Execute the `Cuberite` binary.

### Reference:
- https://github.com/MichaIng/DietPi/issues/3664#issuecomment-657019838

I'm pulling @CactiChameleon9 here since I'm not able to run tests on an armv6l RPi model, only armv7l, where it works fine. But the error message is typical for running ARMv7-only (i.e. what Debian understands to be `armhf`) compiled binaries on an this special armv6hf architecture that RP1/Zero is. Builds need to be done on a Raspbian system or with Raspbian build tools, else the binary will fail on mentioned RPi models. The fact that replacing the executable only with a self-compiled one solves the issue, is pointing into the same direction.

**Comment by CactiChameleon9** [comment] 2020-07-12 11:51
I should be able to test new versions if that helps (although do not expect my results to be immediate, same week at the latest - but normally sooner)

**Comment by bearbin** [comment] 2020-07-12 12:12
I can confirm the cause of the issue is as described - the binary version of cuberite is cross-compiled using debian's gcc (although with rasbpian environment) which does not support old RasPis. This is because the current cross-compilation toolkit for Raspbian contains an ancient C++ compiler which is no longer compatible with cuberite.

There may be a workaround possible but unless there's a lot of demand for this to be fixed I would be tempted to leave things as they are.

**Comment by MichaIng** [comment] 2020-07-12 13:40
> There may be a workaround possible but unless there's a lot of demand for this to be fixed I would be tempted to leave things as they are.

If so, then there is actually no need to stay with Raspbian toolkit at all, since on armv7l RPis, regular Debian armhf binaries work just fine, probably better due to armv7l specific benefits.

However from existing users point of view, and since you publish these special "raspi" builds, I hope that you find a way to keep/re-add armv6l support. But sadly I have not enough insights for an idea, besides doing the builds on a Raspbian system, which of course is not an easy option for automated builds.

**Comment by Titaniumtown** [comment] 2020-07-12 16:45
Why not just compile it yourself?

**Comment by CactiChameleon9** [comment] 2020-07-12 16:47
I have been.... but it is really slow to compile. :D

**Comment by bearbin** [comment] 2020-07-12 17:44
I am going to close this issue now for the reasons above - if anyone else runs into this issue, please ping me here and if there is enough demand I will look into a workaround.

**Closed by bearbin** 2020-07-12 17:44 UTC

**Comment by MichaIng** [comment] 2020-07-12 18:00
> Why not just compile it yourself?

Since you have a nice [compile.sh](https://github.com/cuberite/cuberite/blob/master/compile.sh), good point, anyway. Requires a few build tools, takes much longer on SBCs of course, so grab a coffee and watch your favourite TV show before coming back to it 😄.

**Comment by JoshuaRogetsWithPieAndSauce** [comment] 2020-09-08 10:28
Can you leave more detailed instructions for the raspberry pi 0 please

**Comment by MichaIng** [comment] 2020-09-08 10:45
Not tested but that should do it:
```
apt update
apt install git make cmake clang
sh -c "$(curl -sSfL https://compile.cuberite.org)"
```
