### ISSUE TITLE
Chests invisible after teleporting with Portals V3 Plugin

### ISSUE THREAD

**Issue by beezTEM** [cuberite/cuberite#3646] opened 2017-03-25 02:42 UTC
Client version:   1.11.2
Server OS:        RaspberryPi
Commit id:        96663d35b20b6d0cafdb132c920eceeff779fe5a

### Expected behavior
Chests to be visible after using a portal

### Actual behavior
Chests invisible after using a portal

### Steps to reproduce the behavior
1. Install [Portals V3 Plugin](https://forum.cuberite.org/thread-2484.html)
2. Create a portal anywhere
3. Place a chest and create a Portal Destination Next to it
4. Connect the portal and destination and go through the portal

**Comment by Seadragon91** [comment] 2017-03-25 06:34
Duplicate of #3403.

**Closed by Seadragon91** 2017-03-25 06:34 UTC
