### ISSUE TITLE
Segmentation fault on Raspberry Pi 3B+

### ISSUE THREAD

**Issue by sug0** [cuberite/cuberite#4367] opened 2019-08-10 15:47 UTC
Client version:   x.x.x
Server OS:         Void Linux 4.19.63_1 aarch64 GNU/Linux
Commit id:        e7016b15259f8432e0a333a948498fb280d4d7a9

The server program won't load the world. It'll crash with a segmentation fault upon trying to generate it.

I built Cuberite using the provided instructions in the user manual for "manual compilation".

![crash](https://user-images.githubusercontent.com/13282069/62823889-65d94a00-bb8e-11e9-8986-38fcf04dec31.png)

**Comment by sug0** [comment] 2019-08-10 15:50
![crash](https://user-images.githubusercontent.com/13282069/62823929-ffa0f700-bb8e-11e9-8354-eb314ca0a899.png)

**Comment by Seadragon91** [comment] 2019-08-10 16:00
I see that you are using Void Linux and I read that it uses musl instead of glibc.
Same problem like in issue #3406.

The problem is the stack size of a thread in musl is limited to 80k and this is to small. In a other linux like system that uses glibc, the stack size is between 2 - 8 MB.

**Comment by sug0** [comment] 2019-08-10 16:05
I see. Is there a way to increase the size of the stack with some environment variable?

**Comment by Seadragon91** [comment] 2019-08-10 16:30
I don't know. One idea would be to download musl, change the stack size, recompile and install it.

**Comment by sug0** [comment] 2019-08-10 16:32
I'm using a chroot to recompile the server. I'll report whether or not it's working once I've finished it. Thanks!

**Comment by Seadragon91** [comment] 2019-08-10 16:42
The stack size is defined in file `src/internal/pthread_impl.h` the line with `#define DEFAULT_STACK_SIZE 131072`. Looks like it was changed to 128k.

**Comment by sug0** [comment] 2019-08-10 19:02
Hey! Just wanted to let you know that building against glibc solved the problem! For any users experiencing the same problem I did under musl, just create a chroot. It's probably the most straightforward solution.

**Comment by peterbell10** [comment] 2019-08-10 19:06
Thanks for the update @sug0. Closing as duplicate of #3406.

**Closed by peterbell10** 2019-08-10 19:06 UTC
