### ISSUE TITLE
Animals don't follow the Player (with item in his hand)

### ISSUE THREAD

**Issue by Xenoxis** [cuberite/cuberite#4602] opened 2020-04-02 21:05 UTC
Client version: 1.12.2
Server OS: Ubuntu 16.04 server i386
Cuberite Commit id: 318d31dc394da9faea11544ad6e485f1b5eabbdb

### Expected behavior
Expected that cows (and generally all animals) follow the Player if he get Wheat (or other item) in his hand

### Actual behavior
Animals don't follow the Player even if he got the good item in his hand.

See : https://minecraft.gamepedia.com/Breeding#Mechanics

**Comment by mathiascode** [comment] 2020-04-02 21:38
Duplicate of #3041

**Closed by mathiascode** 2020-04-02 21:38 UTC
