### ISSUE TITLE
Plugins should have a proper SQLite API

### ISSUE THREAD

**Issue by williamhatcher** [cuberite/cuberite#3933] opened 2017-08-21 04:28 UTC
While working on the [Core](https://github.com/cuberite/Core) and [ProtectionAreas](https://github.com/cuberite/ProtectionAreas) plugins, I noticed that they have their own SQL abstraction layer.
I think that there should be a standard SQLite abstraction layer/API similar to the ones in those repos.

**Comment by madmaxoft** [comment] 2017-08-21 13:32
Duplicate of #1395

**Closed by madmaxoft** 2017-08-21 13:32 UTC
