### ISSUE TITLE
Add banners to Cuberite

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#3001] opened 2016-02-11 20:56 UTC
This issue was opened sometime ago, and closed because it wasn't implemented. I'm not sure why, as I thought the issue tracker is both for bugs and features on the to-do list.

So yeah, players told me that they'd like to use banners. Not just for all kinds of creative patterns, but becaues you can essentially use them to create huge writings on buildings, like at storefronts.

**Comment by Seadragon91** [comment] 2016-02-11 21:46
Well here is a open one #1535.

**Comment by jammet** [comment] 2016-02-11 22:14
That's odd, it looked like it was closed before I submitted this. I wasn't able to comment on it.

**Comment by NiLSPACE** [comment] 2016-02-12 07:41
Perhaps you're confused with #2967

**Comment by LogicParrot** [comment] 2016-02-12 16:03
Duplicate of #1535, closing.

**Closed** 2016-02-12 16:02 UTC
Labels: blocks
