### ISSUE TITLE
android app does not work

### ISSUE THREAD

**Issue by mrbesen** [cuberite/cuberite#4313] opened 2019-02-13 20:22 UTC
Client version:   -
Server OS:        Android 5.1.1
Commit id:        -

### Expected behavior
Installing the Server binary

### Actual behavior
Starts downloading and then stops (some times the message: "Download error:Download error:" is displayed)
I got the stack trace with logcat
```D/Cuberite/MainActivity( 2673): Getting State: NEED_DOWNLOAD_SERVER
D/Cuberite/MainActivity( 2673): Changing color from ff1e88e5 to ff1e88e5
D/Cuberite/MainActivity( 2673): Getting preferred ABI: armeabi-v7a
I/Cuberite/InstallService( 2673): Downloading NEED_DOWNLOAD_SERVER
D/Cuberite/InstallService( 2673): Acquiring wakeLock
D/Cuberite/InstallService( 2673): Started downloading https://builds.cuberite.org/job/cuberite/job/master/job/android/job/release/lastSuccessfulBuild/artifact/android/Server/server.zip
V/WindowManager(  838): not Base app: Adding window Window{23662d0f u0 Downloading Cuberite…} at 10 of 17
D/Cuberite/InstallService( 2673): Finished downloading
D/Cuberite/InstallService( 2673): Releasing wakeLock
D/Cuberite/InstallService( 2673): Acquiring wakeLock
D/Cuberite/InstallService( 2673): Started downloading https://builds.cuberite.org/job/cuberite/job/master/job/android/job/release/lastSuccessfulBuild/artifact/android/Server/server.zip.sha1
D/Cuberite/InstallService( 2673): Finished downloading
D/Cuberite/InstallService( 2673): Releasing wakeLock
V/WindowManager(  838): not Base app: Adding window Window{20e28b2b u0 Downloading Cuberite…} at 11 of 18
D/Cuberite/InstallService( 2673): SHA-1 check passed successfully with checksum f063ef94e1fafc8a097f89d03dbc16456b5c051f
I/Cuberite/InstallService( 2673): Unzipping /data/data/org.cuberite.android/files/server.zip to /
D/Cuberite/InstallService( 2673): Acquiring wakeLock
E/Cuberite/InstallService( 2673): An error occurred while installing Cuberite
E/Cuberite/InstallService( 2673): java.io.FileNotFoundException: /BACKERS: open failed: EROFS (Read-only file system)
E/Cuberite/InstallService( 2673): 	at libcore.io.IoBridge.open(IoBridge.java:494)
E/Cuberite/InstallService( 2673): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
E/Cuberite/InstallService( 2673): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:127)
E/Cuberite/InstallService( 2673): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:116)
E/Cuberite/InstallService( 2673): 	at org.cuberite.android.InstallService.unzip(InstallService.java:250)
E/Cuberite/InstallService( 2673): 	at org.cuberite.android.InstallService.onHandleIntent(InstallService.java:76)
E/Cuberite/InstallService( 2673): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/Cuberite/InstallService( 2673): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/Cuberite/InstallService( 2673): 	at android.os.Looper.loop(Looper.java:135)
E/Cuberite/InstallService( 2673): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/Cuberite/InstallService( 2673): Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
E/Cuberite/InstallService( 2673): 	at libcore.io.Posix.open(Native Method)
E/Cuberite/InstallService( 2673): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
E/Cuberite/InstallService( 2673): 	at libcore.io.IoBridge.open(IoBridge.java:480)
E/Cuberite/InstallService( 2673): 	... 9 more
D/Cuberite/InstallService( 2673): Releasing wakeLock

```

### Steps to reproduce the behavior
1. install app
2. press install Cuberite

I hope this is the correct place to report this.

**Comment by Cl1608Ho** [comment] 2019-02-17 08:28
It seems to be unpacking your server.zip (which contains all the files you need for a server, like config, etc except for the binary) to /, the root file system. Intended behaviior would be install to your so called external storage (storage shared between all apps, optionally on an external medium like an SD card). As far as I recall external storage might not exist on all devices (like, if mapped to a physical card, if the card is removed?) but might also mean a permission error. I just confirmed this is working on my device, I'll leave it to better error handling and recovery if some expected features are not available on a specific device.

**Comment by mathiascode** [comment] 2020-02-22 21:58
Fixed in https://github.com/cuberite/android/commit/6baa422e0db05f02b4ea61c5e0b2c1ec75ec1035

**Closed** 2020-02-22 21:58 UTC
