### ISSUE TITLE
Placing a Tradoor on top of a half block crashes server

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#4883] opened 2020-09-17 20:47 UTC
Client version: 1.11.1
Server OS: Windows
Cuberite Commit id: 53549a1a4ce320c1e3f449165c290c74d3de54d4

### Expected behavior
No Crash

### Actual behavior
Server Crashing

### Steps to reproduce the behavior
Place a trapdoor on top of a slab

### Server log
```
[7c1b985148b723c6|22:45:09] Assertion failed: !"Unhandled block face!", file C:\Users\Test\CLionProjects\cuberite\src\Bl
ocks\BlockTrapdoor.h, line 113
```

**Comment by bearbin** [comment] 2020-09-17 22:47
Appears to be duplicate of #4878

**Closed by bearbin** 2020-09-17 22:47 UTC
