### ISSUE TITLE
Add enchantment effects

### ISSUE THREAD

**Issue by tonibm19** [cuberite/cuberite#1257] opened 2014-07-29 18:25 UTC
To complete the encanting system, enchantment effects should be implemented.
daniel0916 started with it, but he didn't finish it, so maybe his branch could be useful.
https://github.com/daniel0916/MCServer/tree/Enchanting (see commits)

**Comment by Rakete1111** [comment] 2015-05-31 12:43
Could someone explain to me want Enchantment Effects are?
They don't appear to exist.
What do you mean?

**Comment by bearbin** [comment] 2015-05-31 14:29
Probably so that enchantments will actually do something.

**Comment by Bond-009** [comment] 2018-01-06 18:56
Duplicate of #915

**Closed** 2018-01-06 19:21 UTC
