### ISSUE TITLE
The end does not generate 

### ISSUE THREAD

**Issue by Nikita11790** [cuberite/cuberite#4316] opened 2019-02-26 02:45 UTC
Client version:   1.12.2
Server OS:        Mac OS
Commit id:        4f26f653e1ae168a050f3eca3e8073eca3f10367

### Expected behavior
when you join the end you see the full end

### Actual behavior
only a single chunk of end stone

### Steps to reproduce the behavior

go to end

**Comment by Bond-009** [comment] 2019-02-26 06:51
Duplicate of #4056

**Closed** 2019-02-26 09:00 UTC
