### ISSUE TITLE
Flying not always activated when changing to creative mode

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite#4010] opened 2017-09-09 07:12 UTC
Client version:   1.12.1
Server OS:        Linux
Commit id:        5d64451f74af1839177f9b93d76cd393b7a58ad1 

### Expected behavior
The player is always able to fly after changing the game mode to creative.

### Actual behavior
In some cases, the ability to fly isn't enabled.

### Steps to reproduce the behavior
Fall outside the world while in survival mode, and activate creative mode when taking damage in the void.
Swim in lava while in survival mode, and activate creative mode when the "You died" screen shows up.

**Comment by Bond-009** [comment] 2017-09-09 08:54
Duplicate of #3612

**Comment by bearbin** [comment] 2017-09-09 09:13
Closing as duplicate.

**Closed by bearbin** 2017-09-09 09:13 UTC
