### ISSUE TITLE
Cactie grow too fast

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite#2358] opened 2015-07-14 17:32 UTC

**Comment by SamJBarney** [comment] 2015-07-14 17:36
http://minecraft.gamepedia.com/Cactus#Farming

**Comment by NiLSPACE** [comment] 2015-07-14 18:05
More like "Everything that can grow grows too fast."

**Comment by SamJBarney** [comment] 2015-07-14 18:16
Yeah. I think this will be the next bit I take on, once my current pull requests are complete.

**Comment by SphinxC0re** [comment] 2015-07-14 19:18
@SamJBarney You need to be online on IRC for more instant response

**Comment by mathiascode** [comment] 2020-03-19 12:06
Duplicate of #1667

**Closed** 2020-03-19 12:06 UTC
