### ISSUE TITLE
Wooden doors forget open state

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#1944] opened 2015-05-05 22:28 UTC
Like with trapdoors, wooden doors left open will forget about being so, and will mysteriously close themselves (audibly) when you're nearby, interacting with other blocks.

![2015-05-06_00 35 52](https://cloud.githubusercontent.com/assets/11940735/7484318/64ba7a28-f387-11e4-94fa-33ba00b96d4b.png)
![2015-05-06_00 36 16](https://cloud.githubusercontent.com/assets/11940735/7484321/6cbfdd6c-f387-11e4-8f98-10d78968b801.png)

**Comment by NiLSPACE** [comment] 2015-05-05 22:44
Most likely due to the same reason as trapdoors.

**Comment by bearbin** [comment] 2015-05-06 06:28
Dupe of #1887?

**Comment by jammet** [comment] 2015-05-06 06:37
Very likely, but I'm still looking into that, because I did notice that the doors even forget their open state without the server restarting. I did rejoin the server, went to where the doors are, and saw they were still open, manipulated a few blocks downstairs in that building, and then heard them all collectively snap back into closed state.

I've put a few trapdoors there now to see of they act exactly the same.

**Comment by jammet** [comment] 2015-05-06 06:58
Didn't even have to wait long. Yeah they're acting exactly the same, with or without restarting the server.
Same problem, then, yeah.

**Comment by jammet** [comment] 2015-06-10 07:00
So, the trapdoors seem to have learned their lesson. Can we help the doors, too? :)

**Comment by tigerw** [comment] 2015-06-10 10:13
I think the doors should be fixed also - more testing!

**Comment by jammet** [comment] 2015-06-10 10:45
Sadly, they're not. I tested this yesterday and, again this morning. Place
several doors in a room, open them all. Restart the server. They'll either
already have closed - or one of them. Even if they don't now, if you
interact with any of them, they'll all immediately snap open, as if they
were linked.

They even do that when you open a door above or below them. For instance,
if I enter the house downstairs, and use the door, I already hear the whole
bunch of other doors move, upstairs.

**Comment by tigerw** [comment] 2015-06-10 15:20
Ah yes, I forgot to add door handling.

**Comment by jammet** [comment] 2015-06-10 16:07
:) Thank you for making a simple door very happy.

**Comment by Seadragon91** [comment] 2017-05-08 15:57
Door handling works fine in 1.11.2.

**Closed by Seadragon91** 2017-05-08 15:57 UTC
