### ISSUE TITLE
Can't compile with GCC on Windows

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#4181] opened 2018-02-03 19:15 UTC
Server OS:         Windows
Commit id:        f0c735e8466fbb52bb805dd839f5e4fd37d59af8

I installed cmake, make and GCC with scoop and ran the cmake command to generate the makefiles:
`cmake -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles" ..`
So far so good, then I tried to build:
`make -j8`
and got this error:

```
g++.exe: error: unrecognized command line option '-rdynamic'
make[2]: *** [lib\SQLiteCpp\CMakeFiles\SQLiteCpp.dir\build.make:63: lib/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Column.cpp.obj] Error 1
```

Easy fix, just needed to remove `-rdynamic` from line 46 in cuberite/lib/SQLiteCpp/CMakeLists.txt.
But when I try to build again it spits errors all over the place.
[output.txt](https://github.com/cuberite/cuberite/files/1692091/output.txt)
Hastebin link: https://hastebin.com/iverikiqup.tex

**Comment by pwnorbitals** [comment] 2020-10-09 09:15
@Bond-009 not sure this has been fixed since, can you still reproduce on latest commits ?

**Comment by tigerw** [comment] 2020-10-09 20:26
Last I checked MinGW still had issues compiling, but the exact error listed above was fixed.

**Comment by pwnorbitals** [comment] 2020-10-09 21:00
Could you describe the error message you are having ?

**Comment by tigerw** [comment] 2020-10-12 11:38
Alas I don't have mingw right now, we might have to revisit this when someone else can try.

**Comment by pwnorbitals** [comment] 2021-01-24 11:27
We can probably close this issue, as this didn't seem to bother anyone for a long time

**Comment by bearbin** [comment] 2021-01-24 13:17
Indeed, closing as due to low impact and lack of resources. If this is an issue for anyone else, feel free to reopen and any fixes for this would still be accepted.

**Closed by bearbin** 2021-01-24 13:17 UTC
Labels: poweruser/build system

**Comment by tigerw** [comment] 2021-09-15 22:03
#5295 apparently has some fixes.
