### ISSUE TITLE
Everything has the wrong skin

### ISSUE THREAD

**Issue by rabidlogic** [cuberite/cuberite#4414] opened 2019-10-05 22:05 UTC
Client version:   1.13
Server OS:        CentOS 7.7 (Linux)
Commit id:        241d97bbf952794ba3c5c891f7f37fc5c49cccd3

### Expected behavior
Parrot looks like a parrot. 
Water looks like water. 

### Actual behavior
Water looks like gravel.
Creeper looks like parrot (probably the most terrifying thing. 

### Steps to reproduce the behavior
1. Build Cuberite from source using install.sh
`source ~/.bashrc && sh install.sh -m Release -n yes`
2. Copy built software to another location
cp -r /home/minecraft/cuberite/Server /home/minecraft/cuberiteServer
3. Start up Cuberite
4. Stare confusedly at gravel water and parrot creepers. 

I've rebuilt multiple times on the same server. Not entirely sure what is going on. 

I have the server running. Let me know if you want to take a look and I'll add you to the whitelist.

**Comment by NiLSPACE** [comment] 2019-10-05 23:08
1.13 is only supported to the point that a client can connect. Later on we'll make sure the textures match the actual blocks and entities. The changes for 1.13 were too large to do everything at once.

Connecting with an 1.12 client should work fine in the meantime.

**Comment by 1271** [comment] 2019-11-12 12:42
@NiLSPACE
It would be nice if you could turn off version support somewhere in the settings

**Comment by NiLSPACE** [comment] 2019-11-12 13:11
@madmaxoft made a plugin to do that: https://github.com/madmaxoft/SingleClientVersion

**Comment by madmaxoft** [comment] 2019-12-22 09:39
I'm closing this as a duplicate of #4428, which is a more accurate description.

**Closed by madmaxoft** 2019-12-22 09:39 UTC
