### ISSUE TITLE
Is Cuberite fully functional for 1.12 Client ?

### ISSUE THREAD

**Issue by Kuaaaly** [cuberite/cuberite#3817] opened 2017-06-28 08:24 UTC
Client version:   1.12
Server OS:        Linux (Raspbian Jessie on Raspberry Pi 2)
Commit id:        399ea0bf1de73fbaff31bb11d30e7522ae442710

This issue is not really an issue, and the only question I am asking myself is : **Is Cuberite a fully functional Minecraft server for official 1.12 clients ?**

I you don't have enough time, you can stop reading now and try to answer if you have a point of view on that simple question. If you have some time, may be you can go further.

As you may know, lots of people try to set up a viable Minecraft Server on Raspberry Pi (at least Pi 2 in general). It is my case. Actually, it is just impossible to run a Vanilla server because of the poor optimisation of the code (or may be just because of Java :trollface:). So, many people (like me) use Spigot to set up a Minecraft Server on the Raspberry Pi and, so far, it works... but not that much. It is perfectly working if you're alone, but try to play with a friend (or 2), both of you running in opposite directions during 30 seconds, try to destroy a block of grass and see "how it respawns". That's actually the limit, so let's say a Spigot server allows you to play with friend but you have to (all) be in a few number of close chunks.

So far, Vanilla, Spigot & CraftBukkit servers or not functional on Raspberry Pi (at least version 2). That's why **Cuberite** enter the game !

First of all, I would like to thank you about this amazing work. Yes, Cuberite is amazing, and I'm able to say that even if I know it since the day before yesterday. The reason is that I've just done the single test describe above with my brother (connecting together and running in opposite directions then try to mine) and with the same configuration of the Spigot server : absolutely no lag, no freeze, no spatial jumps or anything like that. So Cuberite appears to me like a really viable alternative to run a Minecraft Server on a Raspberry Pi.

But, I continued playing a bit and started to discover bugs :
- The first I discovered after charging my saved world from Spigot (what was obviously not an easy thing), was the bed bug referenced in this issue (#3787)
- Furthermore, I also noticed that bed colors (1.12 version only) were not functional. The color of the wool you take does not matter you will always craft a white bed that will change to red when you right click it on the floor
- I tried to generate a new world to play a bit with Cuberite and I spawn under water and guess what happens.... 🤣 !

We are now back to my initial question : **Is Cuberite viable for 1.12 clients ?** and if not **Is there a client version you can play fully functional on Cuberite server ?**. According to the web site, forums, and GitHub repository, I thought that Cuberite was fully functional for 1.8 to 1.12 clients but after playing only few tens of minutes I discovered many bugs and I'm looping back to my initial question "what is the good alternative to run a Minecraft server on Raspberry Pi ?".

Finally, a more technical question : I saw in a technical posts that Vanilla servers are not multi-threaded (and Spigot too by the way), that's why is lagging even if it use less than 50% of total CPU capacity. It seems that Cuberite is not multi-threaded too (but I might have not put it in such a pain to see a difference), is that actually true ? I think there is a reason, but which one ?

Thank you for the time you took to read and answer this post, and please, keep up this amazing work.
Kuaaaly

**Comment by Seadragon91** [comment] 2017-06-28 10:15
Short answer: NO. There are many things missing, fully working or implemented.

Here a overview written down from my head, whats missing:
- Many mobs
- Villagers and trading
- Water temple
- Ridding on animals
- Animals have no inventory 
- Different horse types
- End generator
- Features from 1.12 are no implemented
- Also old features, like world border
- NBT is not fully implemented: Block entities, items, mob spawner and more
- Only basic support for command blocks

**Comment by NiLSPACE** [comment] 2017-06-28 11:58
For the reasons listed by @Seadragon91 we usually recommend using Cuberite as a creative server/

> It seems that Cuberite is not multi-threaded

Cuberite is multithreaded. All the different world's have their own threads and the world generator has it's own thread. The last thing can easily be noticed if you use the compass tool from WorldEdit. If you don't know what it does it teleports you to the place you're looking at with the left mouse button. In bukkit/Spigot once you use the tool while at the edge of the generated world the server will be really slow to respond while Cuberite stays responsive.

I also believe the networking is done on another thread, but I'm not sure anymore. @madmaxoft might be able to clear things up when it comes to the threading.

**Comment by madmaxoft** [comment] 2017-06-28 12:08
Cuberite is as much multi-threaded as possible. Splitting into any more threads would be counter-productive. The only thread that can get overburdened is the world tick thread, but splitting its work would mean a collossal amount of synchronizing work and we're not sure if it would help the performance at all; the assumption is that it wouldn't.

Yes, the networking has its separate threads, too, as does the world lighting, chunk storage, online uuid checks and others.

**Comment by Seadragon91** [comment] 2017-06-28 12:11
As for the world generator. I this issue I read that it could be maybe improved by creating a shared thread pool:
https://github.com/cuberite/cuberite/issues/2320

**Comment by Kuaaaly** [comment] 2017-06-28 14:37
Many thanks for all your answers. I'm glad to read that Cuberite is multi-threaded as it was a big lack of the Java version. So actually, Cuberite is not a viable alternative to play with full up-to-date features Minecraft clients, but more a project to optimised Minecraft server and develop a stronger one. As I am a real beginner in development, I didn't noticed that when I first downloaded and installed Cuberit.

May be it is a good idea, that you keep an exhaustive list (on website and/or GitHub) to explicitly mention which are the features that are not actually supported.

So, to conclude this thread : **Do you have any clue on how I could set up a viable Minecraft server on a Raspberry Pi 2 or 3, to play with 5 or less friends simultaneously ? Is that possible or should I get something more powerful ?**

**Comment by NiLSPACE** [comment] 2017-06-28 16:35
Creating such a list is easy, but keeping it up-to-date is the hard part.

I'm not aware of any custom server that has all the feature vanilla has while performing better, so it might be better to upgrade your hardware.

**Comment by yangm97** [comment] 2017-06-28 17:20
Why not both? Right now I’m using cuberite for lobby and creative worlds (soon minigames too) and spigot for survival stuff. I also use bungeecord to make switching between the two easy.

**Comment by spekdrum** [comment] 2017-06-29 08:12
Reading these words one could think Cuberite is not ready for survival gaming. But most of the features from survival mode are working ok. Its not that bad. Also there are people focused on fixing or adding survival functionalities (included myself). I encourage players to give it a try and report missing features / bugs so we can keep the pressure

**Comment by Kuaaaly** [comment] 2017-06-29 08:39
I can confirm that Cuberite is functional for Survival gaming but not fully. Actually my friends want to play on an up-to-date server, that's why I created my topic : to know if this was possible with Cuberite (even if it's now an obviousness for me that was not the case when I installed it the first time).
Here is my actual setup :
- One Raspberry Pi 2 running Spigot 1.12 (but we're actually struggling with it and I plan to move to my Raspberry Pi 3, if we keep struggling we will go to Realms 😭, for simplicity)
- One Raspberry Pi 2 running last version of Cuberite (updated once a week)

So, I will play as much as I can on Cuberite and try to help you improving the great job by reporting missing features or bugs. I would have help you with the code if I were nice developer but I think that my poor C skills are too old for that.

**Comment by LogicParrot** [comment] 2017-08-26 21:20
>Cuberite is as much multi-threaded as possible. Splitting into any more threads would be counter-productive. The only thread that can get overburdened is the world tick thread, but splitting its work would mean a collossal amount of synchronizing work and we're not sure if it would help the performance at all; the assumption is that it wouldn't.

In theory, two players playing in the same world but sufficiently far away from each other may benefit from two tick threads. No synchronization is needed and the world can effectively be treated as "two worlds".

**Comment by yangm97** [comment] 2017-08-27 07:08
> In theory, two players playing in the same world but sufficiently far away from each other may benefit from two tick threads. No synchronization is needed and the world can effectively be treated as "two worlds". Actual implementation could be very complex though.

Looks like a single machine cluster to me. Why would one implement that and not actual clustering?

**Comment by LogicParrot** [comment] 2017-09-11 11:30
>Looks like a single machine cluster to me

It's just a normal threaded program.

>Why would one implement that and not actual clustering?

Because **threads** have synchronization mechanisms such as locks that are not easily available for **processes** or **separate machines**, and because threads can share the same memory, whilst processes or separate machines must use message passing.

All of that makes threads more efficient and/or easier to implement for some use cases.

**Comment by yunfan** [comment] 2017-09-14 08:16
i am running cuberite on my nanopi , which is smaller than rpi, and found that lots of the feature dont work. well, i think it will finally been solved. but there might be another problem i think need to consider . most of these SBCs use a nand flash storage, we need to notice this and try best to avoid destroy the storage by frequently random r/w. 

i havent read the target code for map saving, but i knew that it require libsqlite for compiling, so do you have plan to use a in-disk kv store engine to support map saving? like leveldb or its alternatives

**Comment by bearbin** [comment] 2017-09-14 08:48
Closing this, as the question has been answered. Don't stop your discussion though.

**Closed by bearbin** 2017-09-14 08:48 UTC
Labels: internals/protocol & network, type/question

**Comment by yangm97** [comment] 2017-09-14 16:41
@yunfan maps are stored using the NBT format (aka the same as vanilla). 

What could be done to improve that is add support for PE maps using the mojang fork of leveldb: https://github.com/Mojang/leveldb-mcpe

**Comment by yunfan** [comment] 2017-09-15 02:33
@yangm97 ok, then i think it could be improve by using leveldb too, it looks like minetest use that.

**Comment by yangm97** [comment] 2017-09-15 05:55
@yunfan  If you intend to add leveldb support, make sure it’s compatible with minecraft pocket edition: https://minecraft.gamepedia.com/Pocket_Edition_level_format

Also, I think it’s a good idea do discuss implementation before going into code.

**Comment by yunfan** [comment] 2017-09-16 04:08
@yangm97 i agree we need a discuss for this, but the problem is i just checked the issues of this project, it has a huge number left unsolved, anything happened with this project? or its just grow too fast than before?

**Comment by yangm97** [comment] 2017-09-16 13:56
@yunfan “With great projects comes great amounts of open issues” – Uncle Ben

**Comment by madmaxoft** [comment] 2017-09-18 08:23
As for the storage, it doesn't matter what kind of underlying storage we use, it all boils down to how often a chunk is saved - each save means multiple writes to the storage (update data, update file size / attributes). Doesn't matter if the actual file being changed is a MCA file or a LevelDB file. With current technologies, the solid state storage uses wear leveling, so there's no point of us trying to reinvent the wheel in software for something that the hardware already does for us.
