### ISSUE TITLE
Invisible Horses

### ISSUE THREAD

**Issue by SamJBarney** [cuberite/cuberite#2259] opened 2015-06-18 16:01 UTC
I was  testing my code to kill grass if there is a block on top of it, and I saw a shadow moving around on the ground, not associated with any entity. So I right clicked it, and I mounted it, so I assume it is a horse.

I just tested using the spawn egg for a horse, and I was able to get one of them trapped. 
![2015-06-18_10 00 28](https://cloud.githubusercontent.com/assets/1827860/8235750/f6533fe8-15a0-11e5-8c61-557ddcbeb682.png)

**Comment by madmaxoft** [comment] 2015-06-18 19:16
Save the world and upload it somewhere. Or doesn't it survive world unloading?
I suppose this is caused by some horse metadata being sent wrong, or an off-limits value, so the client has no idea how to render such a horse.

**Comment by SamJBarney** [comment] 2015-06-18 19:19
Here it is: https://www.dropbox.com/s/u6p888nbwlmr6ab/world.zip?dl=0

**Comment by Seadragon91** [comment] 2015-06-18 20:12
Why not invisible creepers? hehehe

**Comment by SamJBarney** [comment] 2015-06-18 20:17
At least we know the client can handle invalid metadata when it comes to horses :+1: 
Makes me wonder if you could do that with other entities as well :)

**Comment by jan64** [comment] 2015-06-19 11:18
I like the invisible creeper idea, very much.

**Comment by jammet** [comment] 2015-06-22 07:29
We already had invisible creepers. I "saw" them not, in January. It was hilarious. XD Not.

Anyway. Yesterday -- the invisible horse happened to me. I used spawn eggs to repopulate the world. Of of them .. simply was completely invisible, except for the shadow. I gave it a quick, merciful death.

**Comment by SamJBarney** [comment] 2015-06-22 15:54
![Feature Bug]
(http://cdn.meme.am/instances/60835984.jpg)

**Comment by tigerw** [comment] 2015-06-22 20:17
A perfectly valid way to deal with issues.

**Comment by bibo38** [comment] 2015-06-26 18:53
Should now not be possible to spawn a invisible horse.
But maybe this could be "feature", so existing worlds won't be fixed.
I think this Bug can be closed.

**Closed** 2015-06-26 18:56 UTC

**Comment by Seadragon91** [comment] 2015-06-26 18:58
@bibo38 It's possible to close the issue trough a pull request if merged. Here a list of [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/).

**Comment by bibo38** [comment] 2015-06-26 20:05
@Seadragon91 Thank you. Nice thing.
