### ISSUE TITLE
invisible ghost monsters attack me

### ISSUE THREAD

**Issue by archtaurus** [cuberite/cuberite#3893] opened 2017-08-03 21:52 UTC
Client version:   1.12
Server OS:        Linux
Commit id:        N/A

### Expected behavior
fair play

### Actual behavior
the server is running on a Raspberry Pi 3.
the client is running on a dell pc with Linux Mint 18.1.

sometimes I can not see some of the monsters while I can fell their attacks and my dog can attack these bad guys that invisible to me. 

After logout and re-login to the server, sometimes they become visible and sometimes they keep invisible.

### Steps to reproduce the behavior
have no idea

**Comment by williamhatcher** [comment] 2017-08-03 23:16
Odd. Can you please update your op with the version number and commit id found near the top of the console output when you start the server?
Ex: 
![capture](https://user-images.githubusercontent.com/24600763/28947858-c1ed21ce-7877-11e7-8ee4-0049179fc782.PNG)

Version: 568
Commit id: ec08bf6255759de3389041c3cbb361b970d3ca7b

Thanks!

**Comment by spekdrum** [comment] 2017-08-04 07:55
This is related with theese issues: #3696 #3609 and #2598

This PR #3745 fixes this problem, but is not merged yet because it's not the right solution. Among other things, It forces that a mob that have seen a player (and is going to attack him) is always visible to the player. You can build your custom version with that PR merged to fix it.

**Comment by LogicParrot** [comment] 2017-08-08 13:58
Can you reproduce this with 1.8?

**Comment by LogicParrot** [comment] 2017-08-24 07:41
Is anyone experiencing this? This is important if still present, but I can't reproduce it.

**Comment by louisgrasset** [comment] 2017-09-06 13:02
I'm getting the same issue (randomly)

**Comment by LogicParrot** [comment] 2017-09-11 11:10
Closing as duplicate of #3696

**Closed by LogicParrot** 2017-09-11 11:10 UTC
Labels: priority/important
