### ISSUE TITLE
End has only end stone

### ISSUE THREAD

**Issue by OwenJF** [cuberite/cuberite#5008] opened 2020-10-24 15:08 UTC
Client version: 1.12.2
Server OS: Windows
Cuberite Commit id: 2231

Spawn on 5*5 obsidian platform, ~10 obsidian pillars with end crystals, bedrock area and a dragon.

Only end stone islands

Enter end

**Comment by 12xx12** [comment] 2020-10-24 15:28
Duplicate of #4056

**Closed** 2020-10-24 15:29 UTC
