### ISSUE TITLE
Objects placed with Steve's left hand don't persist between sessions or drop anything

### ISSUE THREAD

**Issue by qguv** [cuberite/cuberite#4069] opened 2017-11-12 01:02 UTC
Client version: 1.12.2
Server OS: Arch Linux
Commit id: c54bf40ef96806bf836db205f79e60d016b7eee9

### Expected behavior
Items placed with right-click should persist even after logging out and logging back in. Also they should drop the appropriate entity when destroyed.

### Actual behavior
Blocks, torches, and other placed objects don't drop anything if they were placed when the item was in the right-click slot, and they disappear after logging back in.

### Steps to reproduce the behavior

Not persisting between sessions:

Put a torch in the left-hand slot. Right-click to place the torch. Log out and back in. _The torch is gone??!_ sp00ky

Not dropping anything:

Put a torch in the left-hand slot. Right-click to place the torch. Left-click to destroy the torch. Note that _it doesn't drop anything??!_ sp00ky

**Comment by peterbell10** [comment] 2017-11-12 11:19
Duplicate of #3732

**Closed** 2017-11-12 11:19 UTC
