### ISSUE TITLE
Minecart accelleration when manned is not strong enough

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#3015] opened 2016-02-17 12:30 UTC
I remember that most of the tracks used in vanilla have (just straight forward and level surface) 1 powered rail every 32 blocks to keep the cart at reasonable speed.

Right now, I need to put a lot more of them on the tracks to keep it going, as it runs out of steam fairly quickly.

**Comment by bearbin** [comment] 2020-05-03 22:27
Duplicate of #2999

**Closed by bearbin** 2020-05-03 22:27 UTC
Labels: ingame/minecart
