### ISSUE TITLE
1.7.2 Block placement is broken

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2026] opened 2015-05-15 18:40 UTC
Placing dirt works, placing anything else behaves weirdly:
Mobs don't detect the placed blocks, the placed blocks do appear in the server console (when verbose debug mode), and when leaving and rejoining, the blocks aren't there.

**Comment by madmaxoft** [comment] 2015-05-16 08:55
This has already been reported once and we couldn't reproduce it on our side (but I can't find the issue, unfortunately). If you can reproduce it, perhaps you're the best suited to fix it.

**Comment by SafwatHalaby** [comment] 2015-05-16 10:06
I would love to but I am still unfamiliar with the code base outside cEntity and its decedents.
What could be different here? Why would it happen on one computer but not on another?

**Comment by SafwatHalaby** [comment] 2015-05-16 10:16
I reported that other issue, I was mistaken when I said I cannot re-produce it anymore, I simply didn't try anything other than dirt back then.

**Comment by NiLSPACE** [comment] 2015-10-07 14:02
Can we close this?

**Comment by SafwatHalaby** [comment] 2015-10-09 08:37
Let me re-check, I'll close if reproduction fails.

**Comment by SafwatHalaby** [comment] 2015-10-10 13:52
I am still able to reproduce it.

**Comment by LogicParrot** [comment] 2016-02-09 10:54
This is still 100% reproducible, interestingly, sometimes the **Client** crashes, too.

**Closed** 2016-09-07 06:26 UTC
Labels: protocol / network
