### ISSUE TITLE
If you try to place blocks inside of you in 1.9 you will be pushed away.

### ISSUE THREAD

**Issue by mohe2015** [cuberite/cuberite#3340] opened 2016-08-22 14:41 UTC
Client version:   1.9
Server OS:       Linux
Commit id:        approx: 07c5f09ecf2fdf0d84c7cf6862c37b6cc71d4d75 built at: approx: 2016-08-21 11:03:26 +0200

### Expected behavior
You can't place blocks inside of you in 1.9

### Actual behavior
You will be pushed away if you place a block inside of you in 1.9. In 1.8 it works fine.

### Steps to reproduce the behavior
Join server with 1.9. Place any block inside of you.

**Comment by tigerw** [comment] 2016-08-22 14:43
Mojang seems to have let the server decide on whether a client can place a block in an entity or not.

**Comment by mohe2015** [comment] 2016-08-22 14:45
But in 1.8 it works, maybe they changed that.

**Comment by tigerw** [comment] 2016-08-22 14:46
Most certainly.

**Comment by mathiascode** [comment] 2016-08-23 17:11
Duplicate of #3196

**Closed** 2016-08-27 08:23 UTC
