### ISSUE TITLE
Multiple client versions are able to connect to the server without the option to disable certain client versions

### ISSUE THREAD

**Issue by HelenaKitty** [cuberite/cuberite#3525] opened 2017-01-06 13:41 UTC
Client version:   1.10
Server OS:        Linux
Commit id:       c8b1d8a37d6073786df34836ed1e2c88652ac629

From the console output, I have noticed you are supporting several client versions and protocol versions which is a very good idea, however in terms of compatibility you might want to add some sort of explicit control in the config allowing the server admin to select which clients can and can't connect, for example lets we got client versions 12 and 13 which don't have any new items, it would be a good idea to allow both to connect, but then clients such as 1.8 would be missing certain blocks which the servers supports.

[13:33:24] Compatible clients: 1.8.x, 1.9.x, 1.10.x, 1.11
[13:33:24] Compatible protocol versions 47, 107, 108, 109, 110, 210, 315

### Expected behavior
I expect to be able to explicitly set in the config which client versions are allowed to connect to my server.

### Actual behavior
They can all connect anyway!

**Comment by sphinxc0re** [comment] 2017-01-06 13:49
https://github.com/madmaxoft/SingleClientVersion

**Comment by jammet** [comment] 2017-01-07 12:57
How are blocks handled that aren't in all client versions (yet)? 

For example, when a 1.8.9 client connects and looks at what another player with 1.11 has built using purpur blocks?

**Comment by LogicParrot** [comment] 2017-01-09 14:25
This is currently a problem. The plugin above does solves it and is recommended, but it might be better to have something built-in. Relevant links:
 - [Forum - Crash avoidance tips](https://forum.cuberite.org/thread-2504.html)
 - [Github - Handling multiple protocols](https://github.com/cuberite/cuberite/issues/3525)
 - [Forum - Proposal: Allowed protocols configuration](https://forum.cuberite.org/thread-2730.html)

>How are blocks handled that aren't in all client versions (yet)?

Clients handle unknown blocks by not rendering them. There'd be invisible blocks.
Unknown inventory items (e.g. picking up a purpor block) result in client-side crashes. 
There are possibly more issues with multi-protocol, so the single-protocol plugin is highly advised.

**Comment by LogicParrot** [comment] 2017-01-09 14:25
I am closing this because it is a duplicate of the above links.

**Closed by LogicParrot** 2017-01-09 14:25 UTC

**Comment by HelenaKitty** [comment] 2017-01-09 16:59
Excellient, thank you all very much!

**Comment by HelenaKitty** [comment] 2017-01-09 17:00
Which client version is the most supported in terms of blocks, etc?

**Comment by sphinxc0re** [comment] 2017-01-09 17:01
1.8 I'd say

**Comment by jammet** [comment] 2017-01-10 11:51
Thanks. I'll enable this plugin on my server as well, and 1.8 is the choice to go with. Weirdly enough, it doesn't reply to pings at all, at least not right now. Can connect just fine though. I'll retype "Unwanted client version" with "Connect using 1.8.x" just on my end though, just to make sure everyone gets it.
