### ISSUE TITLE
Stepping on processed ground

### ISSUE THREAD

**Issue by lukacat10** [cuberite/cuberite#4434] opened 2019-12-07 14:20 UTC
Client version:   1.12.2
Server OS:        Windows
Commit id:        approx: fb2ef33c89e40e66365db7642bfa06258a61d5ab

### Expected behavior
Stepping on processed ground should turn it into normal dirt

### Actual behavior
Seems to work visually on the client side, but on the server side it is not registered.

Because of that, planting seeds will still work, and reloading the chunk on the client side (requesting it again from the server) will return the ground as processed.

### Steps to reproduce the behavior
Step on processed ground

I might try to do a pull request with a solution to that myself, in the near future

**Comment by madmaxoft** [comment] 2019-12-22 09:28
I assume "processed ground" means farmland? Does it turn to dirt when stepping on it in vanilla? I thought you had to jump / fall on it from height in order to turn to dirt.

**Comment by mathiascode** [comment] 2020-03-18 22:40
Duplicate of https://github.com/cuberite/cuberite/issues/1179

**Closed by mathiascode** 2020-03-18 22:40 UTC
