### ISSUE TITLE
Grass inconsistently drops seeds

### ISSUE THREAD

**Issue by BitOfAByte** [cuberite/cuberite#2935] opened 2016-01-31 00:18 UTC
If a player runs around breaking grass it will have intervals of dropping lots of seeds and intervals of dropping no seeds. It seems to be related to time and not to number of blocks broken.

**Comment by BitOfAByte** [comment] 2016-02-05 18:50
It looks like the bug has to be somewhere in one of these files, or at least related to them.

https://github.com/cuberite/cuberite/blob/master/src/FastRandom.cpp
https://github.com/cuberite/cuberite/blob/master/src/Blocks/BlockTallGrass.h

**Comment by bearbin** [comment] 2016-07-29 14:08
I have confirmed the issue and the cause is that the random results returned by FastRandom are broken. They increment by 1 every 2.5 seconds, and return the same value every time when called within that period.

**Comment by tigerw** [comment] 2016-07-29 14:23
You're suggesting that we managed to botch up the simplest of wrappers over the std random generator?

o_0

**Comment by bearbin** [comment] 2016-07-29 14:27
Well, this is a log of the results from me breaking a line of grass:

![image](https://cloud.githubusercontent.com/assets/1297699/17251479/e7636ed6-55a0-11e6-8512-68be61909717.png)

**Comment by tigerw** [comment] 2016-07-29 14:51
What sort of output do you get if you do

```cpp

	while (true)
	{
		cFastRandom rnd;
		std::cout << rnd.NextInt(8) << std::endl;
		std::this_thread::sleep_for(std::chrono::milliseconds(200));
	}
```

at the start of `cRoot::Start()`?

Also output when in cFastRandom.cpp -> self test -> change the 0 to 1 in the pre-processor if directive?

**Comment by Seadragon91** [comment] 2016-07-29 15:19
Every column  a new run:
```
6  7  0  5  5
5  6  4  1  4
7  5  4  6  3
1  4  1  4  2
3  3  0  5  1
5  2  2  1  0
7  1  4  2  7
1  0  6  4  6
3  7  0  6  5
2  6  2  0  4
0  5  5  2  3
7  4  6  4  2
0  3  2  6  1
4  2  3  7  0
0  1  2  7  7
```

The second and the 5th one, looks interesting :)

**Comment by bearbin** [comment] 2016-07-29 15:27
The self test doesn't compile for me. 

The code in cRoot just led to repetitions of the same number over and over again, no change. It chose a different number every time I restarted though.

**Comment by Seadragon91** [comment] 2016-07-29 15:34
Okay under debian I get always the same number back.

**Comment by tigerw** [comment] 2016-07-29 16:59
Appears to work on Windows, but not Linux. I believe the only difference in that file is the thread local storage attribute. So TLS isn't doing what we think it does, or library/compiler bug?

What happens if you move the cFastRandom object out of the loop, to reuse it? That'll take TLS out of the picture, I believe.

What is the error when compiling the self test?

**Comment by Seadragon91** [comment] 2016-07-29 17:16
@tigerw After taking cFastRandom out of the loop, the output is random under debian.
Also under windows 10, I don't get anymore the count down, looks also random

**Comment by tigerw** [comment] 2016-07-29 17:21
Well. Maybe the random library doesn't like a monotonically increasing seed value..?

**Comment by bearbin** [comment] 2016-07-29 17:29
The compilation error was:

```
/home/bearbin/github/cuberite/cuberite/src/FastRandom.cpp:71:16: error: use
      of old-style cast [-Werror,-Wold-style-cast]
                double avg = (double)sum / ITER;
                             ^       ~~~
/home/bearbin/github/cuberite/cuberite/src/FastRandom.cpp:94:12: error: use
      of old-style cast [-Werror,-Wold-style-cast]
                        Counts[((int)v) % BUCKETS]++;
                                ^    ~
/home/bearbin/github/cuberite/cuberite/src/FastRandom.cpp:104:3: error: no
      previous extern declaration for non-static variable 'g_Test'
      [-Werror,-Wmissing-variable-declarations]
} g_Test;
  ^
/home/bearbin/github/cuberite/cuberite/src/FastRandom.cpp:104:3: error: 
      declaration requires a global constructor
      [-Werror,-Wglobal-constructors]
} g_Test;
```

**Comment by tigerw** [comment] 2016-07-29 17:34
Ah the good ol' ol' style cast.

**Comment by LogicParrot** [comment] 2016-08-04 19:25
I've noticed many times before that random isn't really random when you keep recreating the random generator object. Calling multiple `nextInts on the same object seemed fine.

**Comment by madmaxoft** [comment] 2016-08-04 19:36
We should fix this, it should be possible to instantiate `cFastRandom` for a fast and random generation of numbers.

**Comment by LogicParrot** [comment] 2016-08-04 19:54
In #3151 , a "Chance to get freed this tick" is distributed to all chunks, and some chunks get freed. In previous versions of #3151, things would seem normal sometimes, and sometimes all chunks get mysteriously freed. Sometimes none gets freed when some should. It turned out that `cFastRandom` instantiation was the issue, because each chunk was creating one instance. As you can see in the latest version, I resolved this by having cChunkMap creating one single cFastRandom instance and pass it around to all its chunks sequentially. This produced very good randomness.

**Comment by tigerw** [comment] 2016-08-05 07:38
Why not, use the power of thread_local (hah xoft!) to share a random generator for each world?

**Comment by madmaxoft** [comment] 2017-03-25 17:10
According to test results from #3648 this should be fixed. Setting as in-game testing needed.

**Comment by peterbell10** [comment] 2017-07-21 13:25
Should this be closed? The issue with `cFastRandom` is still there but it isn't actually used anywhere.

**Closed** 2017-07-26 08:24 UTC
Labels: ingame/blocks, status/ingame-testing-needed
