### ISSUE TITLE
Lighting thread assert during spawn prepare

### ISSUE THREAD

**Issue by peterbell10** [cuberite/cuberite#3923] opened 2017-08-13 17:52 UTC
Client version:  N.A.
Server OS:        Linux (Travis-CI)
Commit id:       090914db45ed4bb7d13d5b03718cdc6ea7aa931f

### Expected behavior
Server starts up without crashing.

### Actual behavior
```
Cuberite: ../nptl/pthread_mutex_lock.c:80: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.

Program received signal SIGABRT, Aborted.
```

### Steps to reproduce the behavior
Unknown, happens rarely on travis.

### Relevant thread trace
```
Thread 11 (Thread 0x7fffdffff700 (LWP 10532)):
#0  0x00007ffff6df6c37 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6dfa028 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff6defbf6 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff6defca2 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff71934fc in pthread_mutex_lock ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x000000000060503d in cEvent::Set() ()
#6  0x000000000058faa5 in cLightingThread::LightChunk(cLightingThread::cLightingChunkStay&) ()
#7  0x000000000058f6aa in cLightingThread::Execute() ()
#8  0x00007ffff764e560 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff7191184 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#10 0x00007ffff6ebdffd in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by Seadragon91** [comment] 2017-08-13 17:53
Duplicate of #2891

**Comment by peterbell10** [comment] 2017-08-13 17:54
Is it? the asserts are completely different.

**Closed by Seadragon91** 2017-08-13 17:53 UTC
Labels: crash, internals/lighting

**Comment by Seadragon91** [comment] 2017-08-13 18:00
I saw this assert in a crash no posted, but the stack trace looks similar. Also the stack trace is in the linked travis build.

**Comment by peterbell10** [comment] 2017-08-13 18:08
Oh right. I hadn't seen the linked one.
