### ISSUE TITLE
Stamping on farmland does not revert it back to dirt

### ISSUE THREAD

**Issue by 9caihezi** [cuberite/cuberite#4109] opened 2017-12-25 08:09 UTC
Client version:   1.12.2
Server OS:        Windows
Commit id:        f0b05e78f70fa883bfdc74568bd7bf914025306c

### Expected behavior
Jump on farmland, farm land becomes dirt.

### Actual behavior
Nothing

### Steps to reproduce the behavior
Described as before.

**Comment by peterbell10** [comment] 2017-12-25 17:03
Duplicate of #1179

**Comment by bearbin** [comment] 2017-12-26 10:38
Closing as duplicate.

**Closed by bearbin** 2017-12-26 10:38 UTC
