### ISSUE TITLE
AnimalSpawnChunkPercentage is not took in consideration

### ISSUE THREAD

**Issue by Xenoxis** [cuberite/cuberite#4607] opened 2020-04-03 13:15 UTC
Client version: 1.12.2
Server OS: Ubuntu server 16.04 i386
Cuberite Commit id: 318d31dc394da9faea11544ad6e485f1b5eabbdb

### Expected behavior
I expected that with AnimalSpawnChunkPercentage, more animals will spawn

### Actual behavior
Currently, there is no differences between AnimalSpawnChunk Percentages value of 10, 30 and 50 (values tested)
It seems that the value isn't took in consideration by the server
Moreover, this parameter is undocumented

**Comment by madmaxoft** [comment] 2020-04-03 14:35
Do note that the `AnimalSpawnChunkPercentage` value is only taken into account when (re-)generating chunks, it doesn't apply for already-existing chunks. Also it only applies to the `Animals` finish generator, if you don't have it listed among the generators, it will not be applied.

**Comment by Xenoxis** [comment] 2020-04-03 14:40
Ok i understand better now, is it possible to change the frequency of animals spawning with existings chunks ? if yes i will check it to make a pull request

**Comment by bearbin** [comment] 2020-04-03 20:23
Closing as not a bug. I don't believe it is possible to change the animal spawn rate currently except for through a plugin.

**Closed by bearbin** 2020-04-03 20:23 UTC
