### ISSUE TITLE
Visual studio compile error

### ISSUE THREAD

**Issue by ShrewdSpirit** [cuberite/cuberite#3007] opened 2016-02-14 14:16 UTC
Hello. I'm trying to compile the commit https://github.com/cuberite/cuberite/commit/3c272b55ea1239238ad9726bba9f7dc8b130e545 using Visual Studio 2013. When I start building ALL_BUILD solution, VS gives me this error:

```
Error   37  error C1001: An internal error has occurred in the compiler.    c:\users\shrewdspirit\desktop\cuberite\clone\build\src\BlockEntities\BrewingstandEntity.h   114 1   Cuberite
```

Windows 10 64 bit
Visual Studio 2013 Ultimate
Win32 release configuration

Edit: It compiles with VS 2015 and same config

**Comment by NiLSPACE** [comment] 2016-02-14 15:25
I believe everyone on Windows is using VS 2015, but we should still be supporting VS 2013. If not then we need to update our [Compiling manual](https://github.com/cuberite/cuberite/blob/master/COMPILING.md#windows).

**Comment by ShrewdSpirit** [comment] 2016-02-14 15:34
That's right. But as it says VS 2013 in compiling manual, I thought I should use it instead of VS 2015

**Comment by madmaxoft** [comment] 2016-02-14 17:42
I'm using VS 2013 and I haven't had an error yet. Does it happen again if you do a full rebuild?

**Comment by ShrewdSpirit** [comment] 2016-02-14 18:09
Yes I've rebuilt it many times with VS 2013 and it gives me the same error. I haven't updated VS 2013 toolchain though and it's using the old one. I guess it's not supporting some kind of feature in this version of VS 2013 that I have

**Comment by NiLSPACE** [comment] 2016-02-14 18:59
Maybe I know what's the problem. You also have VS 2015 installed right? Perhaps cmake created a solution file for VS 2015, but you're opening it using VS 2013.

**Comment by ShrewdSpirit** [comment] 2016-02-14 19:33
Yes, I have both but I tell Cmake which VS version to use. For building on VS 2013, I select Visual Studio 12 2013 in Cmake configure menu

**Comment by madmaxoft** [comment] 2016-11-20 20:46
We seem unable to reproduce this bug, and anyway it seems more like a VS bug. Closing.

**Closed by madmaxoft** 2016-11-20 20:46 UTC
Labels: build system
