### ISSUE TITLE
Redstonetorch does not burnout

### ISSUE THREAD

**Issue by mrbesen** [cuberite/cuberite#3749] opened 2017-06-07 15:37 UTC
Client version:   1.10
Server OS:        Linux
Commit id:        7922e6addb06de89cc73c64d30321aa6710e30ce

### Expected behavior
After 10 blink's Redstone torch should burn out and stay unlit.

### Actual behavior
Redstonetorch blinks forever

### Steps to reproduce the behavior
see picture

![grafik](https://user-images.githubusercontent.com/8640309/26887248-c7561546-4ba7-11e7-90be-95b8c43c8dab.png)

**Comment by NiLSPACE** [comment] 2017-06-08 12:18
Duplicate of #2215

**Closed by NiLSPACE** 2017-06-08 12:18 UTC
