### ISSUE TITLE
Implement statistic/achievement triggers

### ISSUE THREAD

**Issue by structinf** [cuberite/cuberite#1008] opened 2014-05-18 20:20 UTC
TODO List:
- achievement.onARail
- achievement.flyPig
- achievement.snipeSkeleton
- achievement.portal
- achievement.ghast
- achievement.potion
- achievement.theEnd
- achievement.theEnd2
- achievement.overkill
- achievement.exploreAllBiomes
- achievement.spawnWither
- ~~achievement.killWither~~
- ~~achievement.fullBeacon~~
- achievement.breedCow
- achievement.diamondsToYou
- stat.leaveGame
- ~~stat.swimOneCm~~
- ~~stat.fallOneCm~~
- ~~stat.flyOneCm~~
- ~~stat.diveOneCm~~
- stat.jump
- stat.animalsBred
- ~~stat.fishCaught~~
- ~~stat.junkFished~~
- ~~stat.treasureFished~~
- cSlotAreaFurnace::HandleSmeltItem

(Assuming #998 gets merged)

**Comment by 12xx12** [comment] 2020-08-10 18:07
Duplicate of #4798
The newer one includes the newer achievements and statistics

**Closed** 2020-09-14 17:13 UTC
