### ISSUE TITLE
f**king flying nocliping mobs ):<

### ISSUE THREAD

**Issue by shibahaczix** [cuberite/cuberite#5378] opened 2022-01-06 16:10 UTC
Client version: 1.8.9
Server OS: debian linux falixnode
Cuberite Commit id: #311

### Expected behavior
zero f**king flying no cliping mobs

### Actual behavior
f**cking flying nocliping mobs 

### Steps to reproduce the behavior
😳its😳just😳doin😳 idk 😳

server log
```     [16:04:30] --- Started Log ---
     [16:04:30] Cuberite Jenkins x86_64-linux-gnu -DCMAKE_BUILD_TYPE=Release (master) (id: #311)
     [16:04:30] from commit efeedcbd4dc2b115ac0737fc397bde64d6b9656a built at: Sun Jan  2 17:01:37 UTC 2022
     [16:04:30] Creating new server instance...
     [16:04:30] Reading server config...
     [16:04:30] Starting server...
Info [16:04:30] Compatible clients: 1.8.x-1.12.x
Warn [16:04:30] WebServer: The server will run in unsecured HTTP mode.
Info [16:04:30] Put a valid HTTPS certificate in file 'webadmin/httpscert.crt' and its corresponding private key to 'webadmin/httpskey.pem' (without any password) to enable HTTPS support
     [16:04:30] Loaded 789 crafting recipes
Warn [16:04:30] Cannot open file "Protocol/1.14.4/base.recipes.txt", no recipe book recipes will be available!
Warn [16:04:30] Cannot open file "Protocol/1.13/base.recipes.txt", no recipe book recipes will be available!
     [16:04:30] Loaded 1.12.2 380 recipe book
     [16:04:30] Loaded 67 furnace recipes and 66 fuels
     [16:04:30] Loaded 49 brewing recipes
Warn [16:04:30] Invalid biome ("BambooJungle") specified in AllowedBiomes in cubeset file Prefabs/SinglePieceStructures/JungleTemple.cubeset. Skipping the biome.
Warn [16:04:30] Invalid biome ("BambooJungleHills") specified in AllowedBiomes in cubeset file Prefabs/SinglePieceStructures/JungleTemple.cubeset. Skipping the biome.
     [16:04:30] -- Loading Plugins --
     [16:04:30] [Core] Initialised!
     [16:04:30] [ChatLog] Initialized ChatLog v.3
     [16:04:30] -- Loaded 2 Plugins --
Warn [16:04:31] World "world_the_end": Did not find an acceptable spawnpoint. Generated a random spawnpoint position at {0, 66, 0}
Info [16:04:31] WebAdmin is running on port(s) 8080
     [16:04:31] Startup complete, took 1221ms!
     [16:04:47] Shutting down server...
     [16:04:47] [Core] Disabling...
     [16:04:47] Cleaning up...
     [16:04:47] Shutdown successful!
     [16:04:47] --- Stopped Log ---

Relevant part of server log
```?






https://user-images.githubusercontent.com/97233130/148413605-4a8ce12e-25cd-4d07-b2e7-f7a35685eac4.png

https://user-images.githubusercontent.com/97233130/148413613-08d0a13c-e659-4e82-8662-a636dd9607aa.png

https://user-images.githubusercontent.com/97233130/148413619-7b127f36-dceb-4dc5-afdd-292b6d0c52a7.png

https://user-images.githubusercontent.com/97233130/148413622-49d948a0-ce03-436e-b38d-64b8d409a5bf.png

https://user-images.githubusercontent.com/97233130/148413624-daad1d15-0b7a-4842-ba3e-8e1bf8650a54.png

**Comment by 12xx12** [comment] 2022-01-06 16:14
Duplicate of #5030 and #3747 and....

**Closed by 12xx12** 2022-01-06 16:14 UTC
