### ISSUE TITLE
Crops not growing/vanished

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#3583] opened 2017-02-23 23:03 UTC
Client version:   1.9.4
Server OS:        RPi
Commit id:       1c31cb7eecc92d2fb218da8948e3201b618a46d2

### Expected behavior
Crops will grow.

### Actual behavior
The farmland where crops are supposed to be, have been emptied about 80% after upgrading from a months older version. Crops are not sparse. Replanted crops where previously planted crops would have been, do not grow. Maybe they are still there, but invisible.

**Comment by mathiascode** [comment] 2017-02-25 18:13
Any difference after https://github.com/cuberite/cuberite/pull/3576 was merged?

**Comment by madmaxoft** [comment] 2017-02-25 18:16
Most likely not, that PR didn't change any underlying logic, it was only a code reformat.

**Comment by madmaxoft** [comment] 2017-02-25 18:17
This should be pretty easy to track down in a debugger - Add breakpoints for the crops manipulation and then connect with a client and test planting, bonemealing and breaking crops. Marking as Easy.

**Comment by denmark111** [comment] 2018-02-19 03:07
Is this issue solved? 
I cannot reproduce the issue in windows server & client

**Comment by jammet** [comment] 2018-02-19 06:51
Well, it was more or less solved by destroying the dirt blocks, putting them back, and re-planting everything. I didn't know what else to do. After that, everything grows normally.

**Comment by mathiascode** [comment] 2020-03-01 09:33
Haven't seen any recent reports, closing.

**Closed by mathiascode** 2020-03-01 09:33 UTC
Labels: effort/easy, ingame/blocks
