### ISSUE TITLE
If trying to attach button, lever etc.. to some items side, it immediately drops

### ISSUE THREAD

**Issue by brother0105** [cuberite/cuberite#4239] opened 2018-06-08 08:38 UTC
Client version:   1.12.2
Server OS:        Linux
Commit id:    

In vanilla server, buttons, levers, torches, etc. which is not block shape can not be placed on top or side of things like torch, flowers etc.(if trying to do that, nothing happens)

But in cuberite, it is destroyed as soon as it is attached and dropped in item form. And 

I think it is bug because if trying to attach torch to side of torch, nothing happens in cuberite either like vanilla server.

### Expected behavior
If trying to attach some items(like button, torch, redstone torch, pressure plate etc.) to other small blocks(like torch, flowers etc.), just swinging hand and nothing happens

### Actual behavior
![image](https://user-images.githubusercontent.com/37765909/41147310-07bd9334-6b41-11e8-9777-472290571e85.png)
![image](https://user-images.githubusercontent.com/37765909/41147934-9f66ee14-6b42-11e8-8a62-165246fd5c34.png)
![image](https://user-images.githubusercontent.com/37765909/41147948-a4518d8a-6b42-11e8-8caa-05857a9c4241.png)
![image](https://user-images.githubusercontent.com/37765909/41147571-b39e5d96-6b41-11e8-94b5-8d8462112461.png)

In that pictures, that attached things were immediately changed into item and dropped

**Comment by tigerw** [comment] 2018-06-30 18:02
Indeed, it seems to be a regression introduced by a recent version of Minecraft no longer checking for invalid placements clientside, which the original code (https://github.com/cuberite/cuberite/commit/a8a45a4afc615926a705eee482c27ef166f2f9ec) assumed.

Probably would have to go through all the handlers and do the proper FullyOccupiesVoxel checks.

**Comment by tigerw** [comment] 2018-06-30 18:03
Originally the client also played a small animation when you tried to place something you couldn't (the hand bobbed down and up), I wonder if this has to be explicitly sent now?

**Comment by changyongGuo** [comment] 2018-07-11 10:39
This issue is caused by incorrect block type check in block handler method  GetPlacementBlockTypeMeta, I will create a pull request to fix this.

**Comment by tympaniplayer** [comment] 2018-08-12 00:08
#4255 seems to be a duplicate of this one. The same behavior is exhibited for lillypads.

**Closed** 2021-05-05 13:25 UTC
Labels: ingame/blocks
