### ISSUE TITLE
SendBlockChanges should split if the packets gets too big.

### ISSUE THREAD

**Issue by NiLSPACE** [cuberite/cuberite#1532] opened 2014-10-11 19:19 UTC
If the MultiBlockChange packet gets too big the client will crash. It should split the packet before it reaches that size: ![Pic](http://puu.sh/c8q5L/8450e95a7f.png)

**Comment by tigerw** [comment] 2021-04-11 13:43
Duplicate of #1249, fixed by ce6219530a2a3e6550967b21bad8ad9a2145c465

**Closed by tigerw** 2021-04-11 13:43 UTC
Labels: internals/protocol & network
