### ISSUE TITLE
Feature request: Armor points

### ISSUE THREAD

**Issue by GefaketHD** [cuberite/cuberite#4659] opened 2020-04-16 16:27 UTC
In vanilla you get a row of armor-points when you have armor on. In cuberite this isn't implemented yet.

**Comment by peterbell10** [comment] 2020-04-16 16:28
Duplicate of #4098

**Closed by peterbell10** 2020-04-16 16:28 UTC

**Comment by GefaketHD** [comment] 2020-04-16 16:41
Oh...

**Comment by Titaniumtown** [comment] 2020-04-16 16:42
smol brain, always search your issue before making an issue.

**Comment by GefaketHD** [comment] 2020-04-16 16:42
:) Thank you
