### ISSUE TITLE
Skin problem

### ISSUE THREAD

**Issue by rowanan45** [cuberite/cuberite#3493] opened 2016-12-26 12:51 UTC
So i try to play minecraft 1.8 but i saw my skin is being weird
And i notice Cuberite still hasn't support the new skin system (including overlay layer[layer 2] , Alex)
That make my skin so weird and someone found this bug in 2015 but still has not fix it..

**Comment by LogicParrot** [comment] 2016-12-26 18:08
Duplicate of #2149

**Closed by LogicParrot** 2016-12-26 18:08 UTC
