### ISSUE TITLE
Add "reload <pluginname>" console command ($5)

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/cuberite#365] opened 2013-11-22 19:21 UTC
The reload console command reloads all plugins. It is, however, possible to reload a single plugin, either by unloading and loading it, or by creating a special plugin-reload function.

This will be useful for developing plugins, since only the relevant plugin can be reloaded, thus making the operation faster and possibly automate-able through RCON.

**Comment by Schwertspize** [comment] 2015-12-01 20:17
fixed now?

**Comment by madmaxoft** [comment] 2015-12-02 08:11
No, it's not implemented yet. Bearbin's commits didn't make it to master, because they didn't work.

**Comment by bearbin** [comment] 2016-03-02 19:35
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=5386204)](https://www.bountysource.com/issues/5386204-add-reload-pluginname-console-command?utm_source=5386204&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Schwertspize** [comment] 2016-03-02 19:39
Maybe boutny tag but we got bug bounties?!? (and for such things, not for more important ones like 1.9?)

**Comment by bearbin** [comment] 2016-03-02 19:41
This bounty was added a while ago, I just added the badge to the issue to let everyone know.

I agree that 1.9 is a issue that could do with a bounty, would you like to add one? (anyone can put up a bounty for an issue)

**Comment by Schwertspize** [comment] 2016-03-02 19:49
Hehe if only I had the money :)

**Comment by ard1998** [comment] 2017-01-23 15:33
can we transfer all ingame commands to an plugin? or if it isn't done alreade, move them to the core plugin as far as possible?

**Comment by sphinxc0re** [comment] 2017-01-23 15:47
Nearly every game related command lives inside the [Core](https://github.com/cuberite/Core) plugin. All _housekeeping_ commands including this one should live inside the server itself

**Comment by ard1998** [comment] 2017-01-23 15:51
can't we just add another command binding?

**Comment by sphinxc0re** [comment] 2017-01-23 15:57
The problem is that you might want to load/unload/reload the Core plugin itself

**Comment by ard1998** [comment] 2017-01-23 16:00
well, what should be the difference between using `reload` what will reload every plugin or using `reload core`

**Comment by sphinxc0re** [comment] 2017-01-23 16:13
No matter what, the reload has to happen from outside the plugin or else we would be forced to give plugins the ability to reload other plugins

**Comment by LogicParrot** [comment] 2017-01-23 17:10
It is not possible to implement this as a plugin because a plugin only has access to the Lua API and this command requires internal access. However, it is possible to create a Lua binding after this is done in C++, and that raises a question: Should plugins have the ability to reload other plugins?

**Comment by madmaxoft** [comment] 2017-01-23 17:15
They already do have that ability - they can execute any console command, including `reload`.

**Comment by LogicParrot** [comment] 2017-01-23 17:24
I see.

**Comment by pwnorbitals** [comment] 2020-09-27 10:39
What was wrong with @bearbin’s implementation ? Did it trigger an error ?

**Comment by tigerw** [comment] 2020-09-27 11:22
I think it was that the existing Unload/Reload functions are async. Reload needs to wait for Unload to finish first, but we have no provision for that.

**Comment by pwnorbitals** [comment] 2020-09-27 17:06
Hoping to get my (first) contribution merged sometime soon to fix this issue

**Closed** 2020-09-27 22:15 UTC
Labels: ingame/commands & ranks & chat
