### ISSUE TITLE
Too many monsters

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#3264] opened 2016-07-15 00:20 UTC
Spawnbehaviour still needs to be tweaked. It's not just the location of monster mobs, but the frequency, and amount.
 
People get swarmed at night on my server, it's really ludicrous at times.  ;) If you remain in a badly lit place in vanilla Minecraft, you will encounter mobs, but not usually a constant onslaught of respawning fresh ones. There be some, but not quite so many.

**Comment by source83** [comment] 2016-07-15 01:39
I have experienced the same thing multiple times too.

**Comment by LogicParrot** [comment] 2016-07-27 08:39
This is a duplicate of #2159

**Closed by LogicParrot** 2016-07-27 08:39 UTC
Labels: ai
