### ISSUE TITLE
Minecraft 1.9: Cuberite Servers not showing up at all in server browser

### ISSUE THREAD

**Issue by jammet** [cuberite/cuberite#3061] opened 2016-03-01 13:31 UTC
They should be listed along with the 1.8 version number, right?

**Comment by bearbin** [comment] 2016-05-16 08:52
This issue should be fixed now, right (since we support the 1.9 protocol).

**Comment by bearbin** [comment] 2016-05-16 08:52
?

**Comment by Pokechu22** [comment] 2016-05-16 14:44
Yes, this is fixed now.  It was caused by the old server list ping format being used, which has been corrected.  Now, attempting to ping a cuberite server from an unrecognized version gives an appropriate version message in the ping.

**Comment by bearbin** [comment] 2016-05-16 14:46
Fixed in #3135

**Closed by bearbin** 2016-05-16 14:46 UTC
Labels: protocol
