### ISSUE TITLE
Can't put out fire.

### ISSUE THREAD

**Issue by reisxd** [cuberite/cuberite#5422] opened 2022-05-07 15:24 UTC
Client version: 1.12.2
Server OS: Windows
Cuberite Commit id: a8ef9d14376fccb4b4b595d52fc9f9c7b5538043

### Expected behavior
When trying to put out the fire, it does it normally.

### Actual behavior
You can't in survival and the block you are looking at also breaks on creative

### Steps to reproduce the behavior
Try to put out fire in survival and creative

**Comment by tonitch** [comment] 2022-05-07 16:13
Hey, thanks for your issue!

It's better to make two separate issue, so contributor can work on them separately if needed! maybe you can close this issue and make two new one each with an issue respectively ?

Also, I tried to reproduce your issues and for me, I could put out the fire by just placing a block on it or by clicking on it (survival or creative). This might looks like a client problem ? have you a modded version of the game ?

I don't really know about the music tho. by making a proper issue we could investigate ^^

thanks for your comprehension

**Comment by tonitch** [comment] 2022-05-07 16:15
ok, I just tried and the music stops as well in single player, it looks like a client feature and not a cuberites bug ^^ 
there is a bug report on the official bug tracker from mojang : https://bugs.mojang.com/browse/MC-99121?jql=text+%7E+%22music+gamemode%22

**Comment by reisxd** [comment] 2022-05-07 17:01
> Hey, thanks for your issue!
> 
> It's better to make two separate issue, so contributor can work on them separately if needed! maybe you can close this issue and make two new one each with an issue respectively ?
> 
> Also, I tried to reproduce your issues and for me, I could put out the fire by just placing a block on it or by clicking on it (survival or creative). This might looks like a client problem ? have you a modded version of the game ?
> 
> I don't really know about the music tho. by making a proper issue we could investigate ^^
> 
> thanks for your comprehension 

I used Minecraft 1.12.2 with Optifine and in TLauncher, didn't worked for me

**Comment by reisxd** [comment] 2022-05-07 17:02
> ok, I just tried and the music stops as well in single player, it looks like a client feature and not a cuberites bug ^^ 
> there is a bug report on the official bug tracker from mojang : https://bugs.mojang.com/browse/MC-99121?jql=text+%7E+%22music+gamemode%22
> 

Yep, thought that after i made this issue lol

**Comment by tonitch** [comment] 2022-05-07 17:07
Nice, I'll look closer when I'm home, maybe you can edit the issue to reflect more (or less) the problem itself then ?
Thanks !

**Comment by tonitch** [comment] 2022-05-08 17:07
for history sake, I will post the video you sent over on discord :

https://user-images.githubusercontent.com/26271060/167307162-a276cae2-28ed-44c4-b3b9-d531542a5ef7.mp4

I personally can't reproduce the issue: 

https://user-images.githubusercontent.com/26271060/167307184-e252e840-d9e6-4e58-969c-390c9b875f7f.mp4

To me, it looks like a client issue, maybe try to play in pure vanilla and see the difference, if the bug doesn't occurs, it is not because of cuberite, if it does, then can you give us a client (mc launcher) and a server (cuberite) log, it would maybe help to find something.

Thanks you!

**Comment by reisxd** [comment] 2022-05-08 17:20
I also tried it in 1.12.1 vanilla and 1.8.9 Optifine and the same issue still occurs, and no I couldn't find any useful client/server log.

**Comment by 12xx12** [comment] 2022-05-08 17:35
Can you log out and in again. Just to be sure that there is an actual fire

**Comment by reisxd** [comment] 2022-05-08 17:38
> Can you log out and in again. Just to be sure that there is an actual fire

https://user-images.githubusercontent.com/29177546/167308460-933d0859-af98-4656-b772-ff2ec5fe37a9.mp4

Still happens.

**Comment by tigerw** [comment] 2022-07-10 14:57
Thanks for the report, think we've found the cause.

**Closed** 2022-07-16 11:04 UTC
