### ISSUE TITLE
Server throws Stacktrace upon shutdown

### ISSUE THREAD

**Issue by HelenaKitty** [cuberite/cuberite#3604] opened 2017-03-01 09:46 UTC
Client version:   1.9
Server OS:        Linux
Commit id:        83fa6cb851536839ebd85b1e91fda928f47eb674

I am sorry for posting here, if this is actually a WorldEdit problem.

### Expected behavior
Server terminates safely and cleanly upon shutdown

### Actual behavior
I have noticed the Stacktrace is thrown upon shutdown if you have used WorldEdit extensively for a while. Server attempts to shutdown, successfully unloads the worlds safely

### Steps to reproduce the behavior
Play around with WorldEdit, kill the server, watch out for a Stacktrace!

### Stacktrace
```[09:40:20]   D:    | Cuberite has encountered an error and needs to close
[09:40:20] Details | SIGSEGV: Segmentation fault
[09:40:20] Cuberite local build build id: Unknown
[09:40:20] from commit id: approx: 83fa6cb851536839ebd85b1e91fda928f47eb674 built at: approx: 2017-02-28 14:07:24 +0100
./Cuberite(_Z15PrintStackTracev+0x14)[0x62fab4]
./Cuberite[0x61b4b3]
/lib/x86_64-linux-gnu/libc.so.6(+0x350e0)[0x7f0a493c20e0]
/lib/x86_64-linux-gnu/libpthread.so.0(pthread_mutex_lock+0x4)[0x7f0a49742234]
./Cuberite(_ZN7cCSLockC1ER16cCriticalSection+0x1e)[0x6294ee]
./Cuberite(_ZN9cChunkMap12GetBlockMetaEiii+0x59)[0x575f19]
./Cuberite(_ZN9cMinecart9DestroyedEv+0x36)[0x8472f6]
./Cuberite(_ZN6cChunkD1Ev+0xc1)[0x568c01]
./Cuberite(_ZNSt8_Rb_treeIN9cChunkMap15ChunkCoordinateESt4pairIKS1_St10unique_ptrI6cChunkSt14default_deleteIS5_EEESt10_Select1stIS9_ENS1_8ComparerESaIS9_EE8_M_eraseEPSt13_Rb_tree_nodeIS9_E+0x218)[0x57c688]
./Cuberite(_ZN9cChunkMapD1Ev+0x1b)[0x572f0b]
./Cuberite(_ZN6cWorldD1Ev+0xd6)[0x616366]
./Cuberite(_ZN6cWorldD0Ev+0x9)[0x616839]
./Cuberite(_ZN5cRoot5StartESt10unique_ptrI28cSettingsRepositoryInterfaceSt14default_deleteIS1_EE+0x888)[0x5e1a38]
./Cuberite[0x61b323]
./Cuberite(main+0xb4)[0x54cd24]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f0a493aeb45]
./Cuberite[0x54fa1c]
[09:40:20]   D:    | Cuberite has encountered an error and needs to close
[09:40:20] Details | SIGABRT: Server self-terminated due to an internal fault
[09:40:20] Cuberite local build build id: Unknown
[09:40:20] from commit id: approx: 83fa6cb851536839ebd85b1e91fda928f47eb674 built at: approx: 2017-02-28 14:07:24 +0100
./Cuberite(_Z15PrintStackTracev+0x14)[0x62fab4]
./Cuberite[0x61b4b3]
/lib/x86_64-linux-gnu/libc.so.6(+0x350e0)[0x7f0a493c20e0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f0a493c2067]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f0a493c3448]
./Cuberite[0x61b4b8]
/lib/x86_64-linux-gnu/libc.so.6(+0x350e0)[0x7f0a493c20e0]
/lib/x86_64-linux-gnu/libpthread.so.0(pthread_mutex_lock+0x4)[0x7f0a49742234]
./Cuberite(_ZN7cCSLockC1ER16cCriticalSection+0x1e)[0x6294ee]
./Cuberite(_ZN9cChunkMap12GetBlockMetaEiii+0x59)[0x575f19]
./Cuberite(_ZN9cMinecart9DestroyedEv+0x36)[0x8472f6]
./Cuberite(_ZN6cChunkD1Ev+0xc1)[0x568c01]
./Cuberite(_ZNSt8_Rb_treeIN9cChunkMap15ChunkCoordinateESt4pairIKS1_St10unique_ptrI6cChunkSt14default_deleteIS5_EEESt10_Select1stIS9_ENS1_8ComparerESaIS9_EE8_M_eraseEPSt13_Rb_tree_nodeIS9_E+0x218)[0x57c688]
./Cuberite(_ZN9cChunkMapD1Ev+0x1b)[0x572f0b]
./Cuberite(_ZN6cWorldD1Ev+0xd6)[0x616366]
./Cuberite(_ZN6cWorldD0Ev+0x9)[0x616839]
./Cuberite(_ZN5cRoot5StartESt10unique_ptrI28cSettingsRepositoryInterfaceSt14default_deleteIS1_EE+0x888)[0x5e1a38]
./Cuberite[0x61b323]
./Cuberite(main+0xb4)[0x54cd24]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f0a493aeb45]
./Cuberite[0x54fa1c]
```

**Comment by madmaxoft** [comment] 2017-03-01 09:58
Doesn't seem like a WorldEdit-related issue, the stacktrace shows a minecart being destroyed.

(Next time please enclose a stacktrace in triple-backticks, I've edited your post for now. It keeps proper linebreaks.)

**Comment by madmaxoft** [comment] 2017-03-01 10:00
It'd be great if you could provide a complete diagnostic for this - see the forum thread for details on how to do that:
https://forum.cuberite.org/thread-631.html

**Comment by Seadragon91** [comment] 2017-03-01 10:05
Maybe related to #3262?

**Comment by madmaxoft** [comment] 2017-03-01 10:05
@Seadragon91 Most likely yes.

**Comment by HelenaKitty** [comment] 2017-03-01 10:22
I'll have to figure which minecart this is seems as nobody has destroyed any.

**Comment by madmaxoft** [comment] 2017-03-01 10:25
It needn't be a minecart explicitly destroyed, it is just when the minecart's representation is released from memory (as part of unloading a chunk on server shutdown)

**Comment by HelenaKitty** [comment] 2017-03-01 10:27
That has better help me to understand the definition of destroyed, thanks!

**Comment by HelenaKitty** [comment] 2017-03-01 10:29
and obviously if I start the server back up, the minecarts are spawned again. I am gonna have a play around with chests.

**Comment by LogicParrot** [comment] 2017-08-21 12:37
I vaguely remember minecart destruction issues in other pull requests / issues, with a hotfix applied by me.

**Comment by LogicParrot** [comment] 2017-08-21 12:38
Chested minecart, perhaps.

**Comment by LogicParrot** [comment] 2017-08-21 12:45
Reference: https://github.com/cuberite/cuberite/pull/3336

**Comment by LogicParrot** [comment] 2017-08-21 12:48
Minor note: [Crash avoidance tips](https://forum.cuberite.org/thread-2504.html) says "avoid chested minecarts".

**Comment by mathiascode** [comment] 2020-05-15 14:14
Presumably fixed or duplicate of https://github.com/cuberite/cuberite/issues/3262. Closing.

**Closed by mathiascode** 2020-05-15 14:14 UTC
