### ISSUE TITLE
Flowers floating on top of snow

### ISSUE THREAD

**Issue by yangm97** [cuberite/cuberite#3539] opened 2017-01-16 15:41 UTC
Client version:   1.8.9
Server OS:        macOS 10.12.2
Commit id:        5ffe920f294360da7dcfc8b4b7198c6e08dd56db

![screen shot 2017-01-16 at 13 35 55](https://cloud.githubusercontent.com/assets/4412002/21989202/2d633980-dbf1-11e6-825d-9e9878846ed3.png)

Additionally, shouldn’t flowers, mushrooms, grass etc. not spawn on snow biomes at all?

**Comment by madmaxoft** [comment] 2017-01-16 15:48
Could you add your world.ini's `[Generator].Finishers` setting?

**Comment by yangm97** [comment] 2017-01-16 15:50
This is a brand new installation, haven’t changed the world.ini, but here it is:

`Finishers=RoughRavines, WormNestCaves, WaterLakes, WaterSprings, LavaLakes, LavaSprings, OreNests, Mineshafts, Trees, Villages, TallGrass, SprinkleFoliage, Ice, Snow, Lilypads, BottomLava, DeadBushes, NaturalPatches, PreSimulator, Animals`

**Comment by NiLSPACE** [comment] 2017-01-16 15:59
Most likely the snow finisher overrides some flowers from the SprinkleFoliage finisher.

**Comment by NiLSPACE** [comment] 2017-01-16 16:01
Could you try the OverworldClumpFoliage finisher instead of the SprinkleFoliage finisher?

**Comment by Pokechu22** [comment] 2017-01-16 17:10
This looks like a double-flower had the bottom block removed but the top block remains.  The actual type of flower could be anything because the top part always switches to that one when the bottom's missing.

**Comment by yangm97** [comment] 2017-01-16 17:48
@NiLSPACE just tried, the issue persisted.

**Comment by yangm97** [comment] 2017-01-16 17:57
![screen shot 2017-01-16 at 15 53 46](https://cloud.githubusercontent.com/assets/4412002/21993854/0bc88e98-dc04-11e6-8240-2115e401b673.png)

Talking about things floating, is this a known issue?

**Comment by NiLSPACE** [comment] 2017-01-16 18:00
I don't see the issue *<sub>builds <sub>a <sub>house on a floating island</sub></sub></sub>*

**Comment by madmaxoft** [comment] 2017-01-16 18:17
Just to make sure, you did re-generate the world after changing the generator parameters, right? :)

As for the floating terrain, that just happens and preventing that would be way too much work for the generator. Just live with it, just like you live with it in vanilla.

**Comment by yangm97** [comment] 2017-01-16 18:20
Yup, deleted all world files except for world.ini.

I thought they fixed that on vanilla, when they made world generation boring.

**Comment by LogicParrot** [comment] 2017-01-16 19:30
Dupe of https://github.com/cuberite/cuberite/issues/1428

**Comment by yangm97** [comment] 2017-01-16 19:40
Did you accidentally close or accidentally reopen?

**Comment by yangm97** [comment] 2017-01-16 22:28
@NiLSPACE sorry only noticed now:
`Warning: [20:26:27] Unknown Finisher in the [Generator] section: "OverworldClumpFoliage". Ignoring.`

**Comment by LogicParrot** [comment] 2017-01-17 05:13
>Did you accidentally close or accidentally reopen?

Accidentally closed. I didn't want to interrupt an ongoing discussion despite the dupe.

**Comment by NiLSPACE** [comment] 2017-01-17 06:20
That's strange, you do have the latest version? It's been in Cuberite for a while though.

**Comment by yangm97** [comment] 2017-01-17 12:44
The commit id is from 3 days ago, so I would say that’s latest enough.

**Comment by HelenaKitty** [comment] 2017-03-01 10:56
Floating islands aren't an issue, I have encountered them a lot on my Anvil world which was originally generated on a spigot server.

**Comment by bearbin** [comment] 2017-09-08 17:00
Fixed by #3545, I believe.

**Closed by bearbin** 2017-09-08 17:00 UTC
Labels: internals/generator
